### ISSUE TITLE
Not working under OS X 10.11.1

### ISSUE THREAD

**Issue by gb160** [NapoleonWils0n/kodi-playercorefactory#1]
Hi, I've followed the instructions and i can't get anything to work.
eg...If i select a stream then choose 'record', the recording doesn't start.
If i look in my kodi log, i see this line:

13:28:09 T:123145303453696  NOTICE: ExecuteAppLinux: ""$HOME/git/kodi-playercorefactory/bash-scripts-macosx/rip-record"" "http://someiptvstreamhere.m3u8" -t 00:30:00 &

if i copy that command into terminal and run it manually, the recording starts as expected, just not from within kodi.

I've verified my .bash_profile is setup as suggested, and i can call the executables (ffmpeg,ffprobe,etc) just fine.
Im using kodi 15.2

Any suggestions?

**Comment by gb160** [comment]
slight update:
It works if i run kodi as root, but not as my normal user.
Its a bit of a pita to have to use terminal to open kodi each time, but it will suffice until a proper solution is found.

Sorry, i should say thanks for this...i had a tacky workaround using vlc to record previously, but i never figured out how to record in the background...using your solution it works fine.(apart from the issue above)

**Comment by primaeval** [comment]
I don't have a mac but check the environment Kodi is running in. $HOME may not point to where you think it does for Kodi. Try to get it to execute something that is in the system path first. Also, check the user that Kodi runs as has permissions for your scripts.

**Comment by gb160** [comment]
@primaeval 
I've checked the scripts are executable by normal user (the same that kodi runs under), but how do i check the environment that kodi is running in?
Cheers.

**Comment by primaeval** [comment]
This page says you need to run ps -wwE -p XXXX where XXXX is kodi's process id. Just run ps to find the pid first. http://chwalisz.org/2013/01/25/osx-show-environment-vars-of-a-running-process/ There is probably some nice mac gui somewhere.

**Comment by gb160** [comment]
Thanks for your assistance solving this.

running that command showed HOME to be as i expected, but it showed PATH to be:
PATH=/usr/bin:/bin:/usr/sbin:/sbin

i just moved the executables (ffmpeg,ffprobe,ffplay) to one of the locations specified above and it now works fine, i no longer need to run kodi as root.

Regards.

**Comment by primaeval** [comment]
:)
