### ISSUE TITLE
Not recording with certain links

### ISSUE THREAD

**Issue by gb160** [NapoleonWils0n/kodi-playercorefactory#100]
Hi mate, got an issue where certain links i have wont record via your scripts, hoping you can offer some assistance.

which i know looks terrifying at first, i think it just consists of a user agent and ridiculously long cookie, the link plays fine in kodi, and i can play them in mpv and ffplay from the terminal, but just no recording.
The link is geolocked to the USA so u might need a VPN to test it.
It'd be really great to get recording working  but i have no idea how to debug your scripts to see what the issue is.

Any assistance is appreciated mate..

**Comment by NapoleonWils0n** [comment]
hi mate

there is a newer version of the recording script written in python called pilfer

https://github.com/NapoleonWils0n/pilfer

i just tried the url with pilfer and it didnt catch the url to record

but it should be possible to match the url with a bit of work

couple of things about the url

the link is url encoded 
so you have this
.m3u8%7C

normally the link would be 
.m3u8|

the other parts are the user agent and cookie

it just a matter of creating a regular expression to extract the cookie code
which we can then pass to ffmpeg

i have a vpn with privateinternet access so i can get round the geo blocking

did you save the url from a kodi addon

could you give me the download link for for the addon or repo
and where the link you are trying to record is in the addon

then i can take a look
cheers

**Comment by gb160** [comment]
Its actually from an IPTV addon, if you have an email i'll send you a copy of the entire m3u ?

I just load the m3u into livestreams pro and watch from there as the rest of the addon is a bit crap

**Comment by NapoleonWils0n** [comment]
hi mate

heres my email
if you send over the m3u8 file ill take a look

t43invisibleman@gmail.com
