### ISSUE TITLE
auto reconnect pvr simple

### ISSUE THREAD

**Issue by mastercleff** [NapoleonWils0n/kodi-playercorefactory#101]
Is it possible to implement auto-reconnect in PVR IPTV SIMPLE CLIENT in KODI?

**Comment by NapoleonWils0n** [comment]
hi mate

i havent really used iptv simple client for years
so i wouldnt know unfortunatly

it would be the built in video player in kodi that iptv simple client uses to play videos
and i dont think it can auto reconnect

i dont think theres a way to auto recconect videos inside kodi

i tend to use playlist loader which lets you add multiple m3u8 playlists

by the way pilfer is the new python version of rip-record
pilfer will catch more urls than rip-record and can also rip audio as well

https://github.com/NapoleonWils0n/pilfer
