### ISSUE TITLE
unistalling and reinstalling 

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#106]
Hi NapoleonWilson,

Sorry to bother you this late, dont know what time it is there but how does a person unistall pilfer and reinstall pilfer to start fresh, and i think i still have rip-record on here, I think, how would i unistall that.
              
                                                                                                                               steve

**Comment by NapoleonWils0n** [comment]
hi steve

uninstall

```
pip3 uninstall --user git+https://github.com/NapoleonWils0n/pilfer.git
```

install

```
pip3 install --user git+https://github.com/NapoleonWils0n/pilfer.git
```

if your on linux you can just remove the rip-record folder to unistall
i dont know about windows

**Comment by steve55792** [comment]
Hope Im not bothering you too late. I apreciate all your help.

**Comment by NapoleonWils0n** [comment]
hi steve

no its midday in the uk

**Comment by steve55792** [comment]
so your like 6 hours ahead almost. I got the pilfer recording 2 shows at once like seconds apart and i didnt see any rip-record folder so I'm good on that. Did you make a video on moving the video to a different folder after it gets done recording,  on youtube? If not how can i do that.

**Comment by steve55792** [comment]
it only took 3 seconds to copy to usb anyways, so no biggie about the video from youtube about recording to different folder.

**Comment by NapoleonWils0n** [comment]
hi steve

no i didnt do any videos on auto moving the videos after recording

if you want to install youtube-dl

on linux it would be 

```
sudo apt install youtube-dl
```

**Comment by steve55792** [comment]
this video i was looking for: https://www.youtube.com/watch?v=-AwmB5XHstM

**Comment by NapoleonWils0n** [comment]
hi steve

yes i remember that one

you create config file with different download location

only works for rip-record as i couldnt work out how to do the same thing with python

**Comment by steve55792** [comment]
oh okay and what a bummer. anyways idid a copy and paste way for the mkv to transfer to a usb . So everything turned out good.

**Comment by steve55792** [comment]
Sorry forgot to ask you earlier will the pilfer work on kodi 18 and do you have the info on about upgrading to kodi 18 on ubuntu?

**Comment by NapoleonWils0n** [comment]
hi steve

i run ubuntu 18 on my laptop

there shouldnt be any reason why pilfer wouldnt work with kodi 18

kodi in the ubuntu is still 17.6 when kodi 18 is released youll be able to upgrade

im think you would have to add the kodi ppa repo and get the latest version of kodi
but i dont really know anything about it 

to be honest id wait until kodi 18 is released and is in the main ubuntu repo

id say having a stable kodi setup is better than bleeding edge version that may have bugs

**Comment by steve55792** [comment]
Good point Thank You NapoleonWilson, you been a big help for me.

**Comment by NapoleonWils0n** [comment]
hi steve

no problem

also addons might not be compatible with version 18 yet

**Comment by steve55792** [comment]
Got both pilfer and rip-record working on linux, now i got to watch the youtube video  on creating config file with different download location for rip-record. Yahoooooooo Lol.
