### ISSUE TITLE
Cant find

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#108]
i tied installing: sudo apt install -y git ffmpeg fdk-aac-dev rtmpdump vlc mpv youtube-dl aria2 inside Ubuntu with the windows 10 bash shell and this happened:
<img width="960" alt="capture3" src="https://user-images.githubusercontent.com/192039/53286546-05686480-3736-11e9-8d45-d83199fb9417.PNG">
Basically it cant find   any comands.

**Comment by Topicform** [comment]
Hi Steve and Jack from Italy... News from pilfer?

Il sab 23 feb 2019, 13:44 steve55792 <notifications@github.com> ha scritto:

**Comment by steve55792** [comment]
I got it fixed.

**Comment by steve55792** [comment]
ok I got the last issue figured out but i got another.  Like i mentioned before i have Ubuntu inside  Windows 10 with the bash shell, the git is stored at LocalState >rootfs>home>bob and the playercorefactory.xml says
$HOME/git/kodi-playercorefactory/bash-scripts/rip-play. What part should i change  to work with ubuntu insde Windows 10?  I Hope I made sense here?
                                                                                                     Steve

**Comment by NapoleonWils0n** [comment]
hi steve

try changing the path to where you hav ethe scripts
and also you need to change the bit of code that goes in your bashrc that adds the path to the scripts

pilfer also comes with a script pilferplay that does the same as rip-play
