### ISSUE TITLE
Not recording on You tube

### ISSUE THREAD

**Issue by Zainpro** [NapoleonWils0n/kodi-playercorefactory#113]
Hello I guess we lost Youtube recording capability...

**Comment by NapoleonWils0n** [comment]
hi mate

pilfer is the new python script to record from kodi

https://github.com/NapoleonWils0n/pilfer


the best tool to record from youtube is youtube-dl

https://github.com/ytdl-org/youtube-dl


aria2c can be used as an external downloader with yourube-dl to speed up downloads

https://aria2.github.io/

**Comment by Topicform** [comment]
Hi dear Napoleon, ffmpeg is very strong and the playercorefactory is a
great revolution. Nice. See you soon.

Il sab 4 apr 2020, 16:05 NapoleonWils0n <notifications@github.com> ha
scritto:
