### ISSUE TITLE
Old files in Kodi Eurosportplayer addon

### ISSUE THREAD

**Issue by Pablowielki** [NapoleonWils0n/kodi-playercorefactory#114]
Hello, Your videos are great, they helped me a lot. My issue is related to Kodi. I have an account on Eurosportplayer and am trying to download some tennis old files (3 months old) from Eurosportplayer. They are available on the website, but not available in the addon (the on demand folder in the addon works fine, but is little bit messy and limited, contains 50-60% of what is on the website). I've tried many methods to download these files, but without any success, I've found one method described here
https://github.com/L4yer/Video-downloader/blob/master/README.md
Your videos and repositories focus on these issues, I think you could give me some guidance.
My questions are: Is it possible to extend the folder in the Kodi Eurosportplayer addon to include these files? or maybe this method described in the above link is worth some attention, but I am struggling to get how to install this requirement.txt file. I would be very grateful for some suggestions.

**Comment by NapoleonWils0n** [comment]
hi mate

re the addon you have 2 choice 

1 - contact the addons developer and ask them to fix it
2 - fix the addon yourself to add the folder, but you would need to know python to do that

re the download script

its not obvious from that page how you install the script
normally they would list the packages you need to install with pip,
i guess there must be another page telling you how to create the requirements.txt file with list of packages to install

your best bet would be to raise an issue on the github page asking how install the script

another thing you could try is logging into the eurosport website with your account
and then opening the network inspector in your browser and play a video and see if you can find the video link

the video link might be a mp4 or m3u8 link, 
if its an mp4 video you could double click the mp4 link in the network inspector which will open the video in a new tab
you can then right click on the video and click save as to download the video

if the video is an m3u8 link you can right click on the link in the network inspector and select copy url

then you could use ffmpeg to download the m3u8 video

```
ffmpeg -i 'm3u8 link' -c copy outfile.mkv
```

replace m3u8 link with the m3u8 link

it also depends if the video use drm or any authentication for the videos if you can download

**Comment by Pablowielki** [comment]
Thank you very much for your suggestions. I will contact the developer, if he doesn't fix it I will try this other suggestion with the network inspector. There is always the last option to learn some python, but I think that it is worth it because whenever they change the on demand folder there will be a problem. So probably it is better to learn some python basics. 
Yes Eurosportplayer uses encryption. I managed to download some files through the addon and your script only.
