### ISSUE TITLE
Kodi 19.4 macOS crashes on any selection from contextual menu

### ISSUE THREAD

**Issue by immetrica** [NapoleonWils0n/kodi-playercorefactory#115]
Dear Mr Wils0n,

Any selection from the contextual menu causes Kodi to crash. The crash logs reference External Player, regardless of the command I select (which is Save URL or one of the Record commands defined in the playercorefactory configuration file).

Please help...

**Comment by NapoleonWils0n** [comment]
Hi Mate

pilfer is the new python version of these scripts to record from Kodi, which works on mac, windows, linux and unix
and also works on the latest version of Kodi

I would recommend switching to the newer pilfer python script as it catches more urls from Kodi,
is faster and more up to date, also i wont be updating the older kodi-playercorefactory bash scripts as development has switched to the newer pilfer python version

pilfer script
https://github.com/NapoleonWils0n/pilfer

pilfer on youtube
https://www.youtube.com/watch?v=uKRU74Uqj1s&list=PL7hhhG5qUoXmtylBpTV4AdjFkYOj2soEB

The way the playercorefactory.xml works changed in kodi 18.6 and you now need to press c on the keyboard on a link and select play with and then select the player, see the video below for details

kodi playercorefactory.xml fix
https://www.youtube.com/watch?v=Q9WvY53D980

Let me know if that helps

**Comment by immetrica** [comment]
Hello, Mr Wils0n,

Thank you. I've been able to save URLs for Netflix and YouTube. However, pilfer won't record either.

Netflix example:

pilfer -i 'http://127.0.0.1:49276/msl/get_manifest?videoid=81246011' -t 00:49:24

(Source programme on Netflix: https://www.netflix.com/watch/81246011 )

YouTube example:

pilfer -i 'https://rr8---sn-8xgp1vo-cvne.googlevideo.com/videoplayback?expire=1651981527&ei=d-h2Ysm-J6GO2LYPleucWA&ip=108.26.181.134&id=o-ADszHzt5Ug7mt2Pqt002zmKl8k9EmpT44Kgb4_XSWVvX&itag=22&source=youtube&requiressl=yes&mh=kK&mm=31%2C29&mn=sn-8xgp1vo-cvne%2Csn-ab5sznzs&ms=au%2Crdu&mv=m&mvi=8&pl=19&initcwndbps=1666250&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=294.057&lmt=1648978975751158&mt=1651959424&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZ5fy3srYEuObTfFAWW_E7j73TSedQ45Wnn3QtT5VgF0CIQDraIFUQxpapnwHxON-1Z1Gz3AkXp0DAgiaBCx0YDvu6Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgNA7R0HUr6PnM61iEspe6WhFStUBVB3WdgkhVwhvxmskCIQCnCFkYywJRerajBDYmv2QO1poShuWjoLYn7KVJl6LF8w%3D%3D|User-Agent=Mozilla/5.0%20%28Linux%3B%20Android%207.0%3B%20SM-G892A%20Build/NRD90M%3B%20wv%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Version/4.0%20Chrome/67.0.3396.87%20Mobile%20Safari/537.36&Accept=%2A/%2A&DNT=1&Accept-Encoding=gzip%2C%20deflate&Accept-Language=en-US%2Cen%3Bq%3D0.5' -t 00:04:53

Source programme on YouTube: https://www.youtube.com/watch?v=g2ySJaPPmlM )

I need to record Netflix and other OTT services' programmes for scientific purposes.

**Comment by NapoleonWils0n** [comment]
hi mate, i would imagine that netflix has drm on the video so you wont be able to record it

use yt-dlp instead of pilfer to record youtube links

you can save the link and then use yt-dlp with the -a option and the text file with the url

```
yt-dlp -a url.txt
```
