### ISSUE TITLE
arch install

### ISSUE THREAD

**Issue by midicase** [NapoleonWils0n/kodi-playercorefactory#119]
In the pacman install aria2c does not exist, should be aria2

**Comment by NapoleonWils0n** [comment]
Hi Mate, aria2 is the package name on arch linux your right
the kodi-playercorefactory scripts have been replaced with a new version called pilfer written in python

im not doing any work on these scripts anymore and development has switched to pilfer
so i would recommend installing pilfer which is more up to date and will match more urls from kodi

pilfer can be installed with python pip and set up in about 5 minutes on linux,
have a look at some of the video links below to get started

[pilfer script to record from kodi](https://github.com/NapoleonWils0n/pilfer)

[pilfer youtube playlist](https://www.youtube.com/watch?v=uKRU74Uqj1s&list=PL7hhhG5qUoXmtylBpTV4AdjFkYOj2soEB)

another nice feature i added was queuing recording using pilfer and taskspooler

[pilfer and taskspooler](https://www.youtube.com/watch?v=L59JSSx1IjQ)

if you have any question or get stuck leave a comment
