### ISSUE TITLE
Open new VLC window each time

### ISSUE THREAD

**Issue by zanesc** [NapoleonWils0n/kodi-playercorefactory#12]
Hi, great work you have done here. I have one question: is it possible to have VLC open in a new VLC window each time i select to play a video with VLC? The issue is that once i select a video to play with VLC, if i try to select another Kodi gets stuck, and only unsticks when I quit the current running VLC window. It would be nice to have a new VLC window open without having to quit the old one.

I'm using Kodi 17 on a Mac.

**Comment by NapoleonWils0n** [comment]
Hi zanesc

yes i found that really annoying as well

here's the fix, 
open vlc preferences and select the all button at the bottom left to show advanced preferences

in the left sidebar select playlist, 
in the right window you will see an option called play and exit select it and click ok
then close vlc

next time you use vlc it should quit automatically after a video has stopped

you can also use mpv player on mac osx

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/macosx#mpv-install

https://www.youtube.com/watch?v=np7yTeOBl3g

hope that helps
