### ISSUE TITLE
Fix Bug in Linux

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#13]
Hi Napole0n,

In you video tutorial No.43, you mentioned a bug with FFMPEG (No Trailing CRLF found in HTTP header) that can't be fixed in windows but can easily be fixed in Linux. 
I appear to be having this same problem in recording streams in Linux Mint, where it only records 1KB.
Can you please let me know how to fix this bug in Linux.

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

Do you error on every stream you try and record or just a particular url

Have you updated ffmpeg recently, sometime i find i have to reboot after updating ffmpeg for things like mpv and ffmpeg to work properly again

Does No Trailing CRLF found in HTTP header appear in the terminal when trying to record
Can you post the addon you are using and the url and ill take a look my end

**Comment by Sparkplugs** [comment]
Hi Napole0n,

The problem occurs when I'm using the 'ITV Player' addon in Kodi.
The url:- 
rtmpe://cp72511.edgefcs.net/ondemand?auth=eaEancSdoaOducNdKckc2avbaaIchcya6buc2bjama4chd_bxbpd2cwaRbpc1dPbMdf-bxv6UA-eS-7zq4GAnmvtFs&aifp=v002&slist=production/ swfurl=http://www.itv.com/mercury/Mercury_VideoPlayer.swf playpath=mp4:production/priority/CATCHUP/Y/2324/0019/003/Y-2324-0019-003_PC011800_16X9.mp4 swfvfy=true

I rebooted my PC and now ffmpeg works (thank you) but only when I select to 'Capture' the stream via mpv, it still doesn't work when I select to 'Dump' the stream directly to my desktop. The file runs to about 5MB, then when the icon changes to a film strip it stops downloading. 
Which, great if you have an easy fix for the no Dump problem....., but otherwise don't sweat it. It's good news that I can still record and save my favourite programs, especially with the Euro's starting soon!

Thanks again
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs
You need to install rtmpdump and then you will be able to record anything from ITV

#### 1 - install rtmpdump

open a terminal and install rtmpdump by pasting the code below in the terminal and pressing return:

```
sudo apt-get install -y rtmpdump
```

#### 2 - git pull to update kodi-playercorefactory scripts

open a terminal and update the scripts by pasting the code below in the terminal and pressing return:

```
cd ~/git/kodi-playercorefactory && git pull
```

#### 3 - copy new playercorefactory.xml to kodi userdata directory

copy the updated playercorefactory.xml from ~/git/kodi-playercorefactory/linux/combined/playercorefactory.xml  

to 

~/.kodi/userdata/playercorefactory.xml

#### 4 - record ITV by pressing y on the keyboard while the video is playing, and then select record, or record 30 mins or record 1 hour etc

#### 5 - if you just select record without a time you will need to stop ffmpeg on the command line by running pkill ffmpeg

stop ffmpeg recording, run command below in the terminal

```
pkill ffmpeg
```

or you can find the process id using this command:

```
ps aux | grep ffmpeg
```

then kill ffmpeg by running kill and the process id you found by running the ps aux | grep ffmpeg command

( replace 1234 with the process id you found with  ps aux | grep ffmpeg  )

```
kill 1234
```

Unfortunately this wont improve the football commentary on ITV or help England to win anything

:)

**Comment by Sparkplugs** [comment]
Hi Napole0n,

That's brilliant, as always. Thank you very much.
Not to put a gypsies curse on it, but I reckon we stand a right good chance this year!

Oh god, I think the gas fires leaking again................

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs

No problem mate, 
always like to make sure everything is working for people

Need to set up a sweep stake on which England player will be added to the list below
- des walker - own goal - italia 90
- chris waddle - penalty miss -  italia 90
- gareth southgate - penalty miss  -  euro 96
- david beckham - sent off - 98
- david seaman - ronaldino free kick - 2002 world cup
- steven gerrard - back pass - world cup 2014

My moneys on Danny Rose or John Stones

Ill mark this issue as closed

:)
