### ISSUE TITLE
rip-play-mpv: xrealloc: cannot allocate 18446744071562067968 bytes (61440 bytes allocated)

### ISSUE THREAD

**Issue by johnp** [NapoleonWils0n/kodi-playercorefactory#18]
Using `kodi-playercorefactory/linux/mpv/playercorefactory.xml` I get the above error. Replacing `[[ -f "$1" ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"` with `VIDEOURL="$1"` works around the error.
`cat`-ing a possibly multi-gigabyte video file into a shell variable seems kinda wrong.

**Comment by NapoleonWils0n** [comment]
Hi johnp

Thanks for catching that bug mate 

I wasn't meaning to cat the video file, 
doh major facepalm

I have come up with some new code which fixes the issue and pushed it to github
could you do a git pull and test it out your end as well

If you have made changes to the code in the git repo you may need to rename the kodi-playercorefactory directory to kodi-playercorefactory-old

And then download the git repo again before testing
- old code:

```
[[ -f "$1" ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"
```
- new code:

```
[[ "$1" =~ \.txt$ ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"
```

Thanks again Mate

**Comment by johnp** [comment]
Just tested locally and Kodi correctly invokes mpv with the updated repository.
Thank you likewise for the quick fix :)

**Comment by NapoleonWils0n** [comment]
HI johnp

Thanks again mate

I will do a new video about the bug fix and tell people to do a git pull to update
And post a note on the Kodi forum as well

http://forum.kodi.tv/showthread.php?tid=216111&page=23

Will give you credit for pointing out the cat issue
Unfortunately there is no bug bounty

:)
