### ISSUE TITLE
Kodi V17 Krypton Alpha 2

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#20]
Hi Napoleon,

Hope you managed to get over England's fiasco swiftly enough. Unless you're like me and just use to the disappointment now.

Just a quick one - I'm currently running Kodi V16.1 and everything is working perfectly with Kodi and the Playercorefactory, thanks to you and your tutorials. 
I was wondering whether or not I should update Kodi to Version 17. Only I don't want to mess anything up but then, I don't want Kodi playing up because it's not been updated.

What do you think?

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Sparkplugs,

Kodi 17 is in Alpha at the moment, 
they usually release the alpha and beta build for people to test and find bugs

Once everything has been tested they will do a proper release of Kodi 17

The Alpha and Beta builds aren't production ready,
shouldn't be used as main machine you rely on

Kodi will be fine running 16.1 and wont start get out of date

i forget what OS you are using, 
if you are running Linux you will get Kodi 17 when its released through your package manager
- eg on ubuntu when you update 

```
sudo apt update
```
- and then upgrade

```
 sudo apt upgrade
```

So id hold off until Kodi 17 is officially released 

#### England

I got used to disappointment with England a long time ago

Same thing every time,
we have a qualifying group with shit teams who we beat 

Then we get to the tournament and lose in the group stages

Harry Kane taking corners, and 5 foot 2 Rahem Sterling trying to head them in
Whats that about, cunning ploy to fool the opposition 

Im part Welsh on my Dads side, so i switched to Wales 
but Wales really missed Aaron Ramsey, never looked like scoring

My Great, Great Grandmother was French, 
so now im switching to France ( is that allowed )

Im pretty fluent in French used to watch an 80s documentary series about life in occupied France under Nazi rule

Have a look in the UK Turks, Tv series 
and search for Allo, Allo

#### fixed cat bug do a git pull to update

I fixed a bug with cat in the scripts, 
which was catting video files by mistake and so using more memory

So do a git pull to update to the latest version where i fixed the bug
- fixed cat bug youtube video

https://www.youtube.com/watch?v=YJew4o-zRqM

All the best mate

**Comment by Sparkplugs** [comment]
Ha Ha Ha........Allo Allo.....classic.

Thanks for the advice, I'll hang fire then until the official release.
