### ISSUE TITLE
scheduling with at

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#22]
I checked out the video of scheduling with at and i thought it was pretty cool of course all your videos are awesome, but back to scheduling with at here I tried:

steve@steve-Satellite-C655D:~/Desktop$ at now + 1 min
warning: commands will be executed using /bin/sh
at> rip-ffmpeg-xforward ~/Documents/schedule/animalplanet.txt<EOT>
job 15 at Thu Jul 14 05:30:00 2016.
am i supposed to download a script "rip-ffmpeg-xforward" 
But no video on desktop.

**Comment by NapoleonWils0n** [comment]
Hi Steve
Just use rip-record, sorry for any confusion
- eg like this

```
at now + 1 min
at> rip-record ~/Documents/schedule/animalplanet.txt
```

and control d to exit

**Comment by steve55792** [comment]
Nothing happened no video on the desktop Here is the url text of animal planet:
http://31.220.40.105:80/LiveEdge/AnimalPlanetUS/chunklist_w2059333313_b1000000.m3u8?securehash=SsiscSj_agPCExKVNKbB83TfwdVfJFTxhG92SLXqGuM%3D&securestarttime=1468489584&secureendtime=1468496784&secureuserid=fc6bd846a2bd5a4ee831624777cf21c7
and i got the saved url text saved in schedule folder in Documents.
Here what I do:
1. Open the terminal
2. Type in cd Desktop
3. Type in    at now + 1 min
4. type in   rip-record~/Documents/schedule/animalplanet.txt

after that the cursor flashes for a few second and it stops.
and control d to exit

**Comment by NapoleonWils0n** [comment]
Hi Steve

you have to start the atd daemon before using at

on ubuntu it should be something like this

sudo service atd start

have a look at this page

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/docs/schedule-recordings

**Comment by steve55792** [comment]
still nothing, do the links expire even tho i got an subscription to Dna Tv on kodi. I tried everything. I even tried playing the channels in the terminal, like if i wanna watch animal planet hit #1 and that doesnt even wanna work unless i refresh the links everytime. my folder of tv links of urls is on the desktop if that might have something to do with it?

**Comment by NapoleonWils0n** [comment]
HI Steve
Some links do expire quicker than others,
often in less than a couple of minutes

url that have .m3u8? usually have some form time based authentication

Also that url has things like securehash, securestarttime and secureid which is usually an indicator it has some kind of time based authentication is in play

things like bbc iplayer usually keep the same urls

best to try and find url that end in .m3u8

its a bit of trial and error to find urls that dont expire,
have to do some testing and find some urls and see how long they last

eg 

no good trying to record a video stream in 2 hours time if the link expires in 5 mins

**Comment by steve55792** [comment]
would this link work, it has an m3u8.
http://31.220.40.114:80/LiveEdge/BoomerangUS/chunklist_w1278719080_b1000000.m3u8?securehash=oxm0DR76vuBp7zkEut8a4tlewh1mZq5c0x0RR5ZMgGo%3D&securestarttime=1468515090&secureendtime=1468522290&secureuserid=fc6bd846a2bd5a4ee831624777cf21c7
how would they play the video that long if it expires within couple minutes

**Comment by NapoleonWils0n** [comment]
Hi Steve

Its the same structure as the other url

i mean ends in .m3u8

eg

http://example.com/video.m3u8

thats the most reliable type

**Comment by steve55792** [comment]
what if i use your m3u playlist creator, would that work with the links to last longer?

**Comment by NapoleonWils0n** [comment]
hi steve

its the url 
wont make any difference what you do with it

**Comment by steve55792** [comment]
what a bumer

**Comment by steve55792** [comment]
even tho the show is 1/2 hour now, if the link expires in 2 minutes, its pointless,

**Comment by NapoleonWils0n** [comment]
Hi steve

Just means you have to start recording before the time authentication kicks in
so if the link expires in 5 minutes as long as you start record before then its fine

but you have to test links and see how long they last before they expire

**Comment by steve55792** [comment]
so when does this link expires, so i would know how to read it.:
http://31.220.40.114:80/LiveEdge/BoomerangUS/chunklist_w1278719080_b1000000.m3u8?securehash=oxm0DR76vuBp7zkEut8a4tlewh1mZq5c0x0RR5ZMgGo%3D&securestarttime=1468515090&secureendtime=1468522290&secureuserid=fc6bd846a2bd5a4ee831624777cf21c7

**Comment by steve55792** [comment]
what if i wanna record a movie on SYFY channel for tomorrow at 6pm even if i saved the url link for that channel in my folder and it expires, do i have to resave. like it expires 10 minutes. am i making sense here?

**Comment by NapoleonWils0n** [comment]
hi steve

unfortunatly there isnt really a way to tell from the url how long the link will last

the only way i know how to test how long the link last is by doing a test recording and see if it works

eg save the url in the morning and set it to record at 6 and see if it works

sorry cant be more scientific, only way i know to see how long the link lasts

there isnt a way to save the url except manually from kodi
i looked at the kodi api but there isnt a way to programalically save the url from addons

i would have a look at  a few different addons like uk turks, ccloud or channel pear
you may find a link for the sci fi channel that doesnt expire staright away
