### ISSUE TITLE
scheduling with at

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#23]
I actually having it recording to desktop with at finally but when time to play the video with any player, it looks like it didnt recorded but it left a .mkv video on desktop, weird.

**Comment by NapoleonWils0n** [comment]
hi steve

thats odd

not sure if the link expired and it created a mkv file with zero bytes

maybe try with a link you know wont expire straight away, something like bbc one from iplayer addon

and schedule to record in 5 or 10 mins time and see if it works

havent used at command for a while

also need to make sure the at daemon or srvice is running

**Comment by steve55792** [comment]
I use the add-on. DNA.Reborn. maybe that is the issue. If you wanna try the add-on to see if that's the issue

**Comment by steve55792** [comment]
Nevermind, cause most of the links in DNA  Reborn addon are working now, for now.
