### ISSUE TITLE
rip-xiptv

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#24]
I dont know what happened but its not working when you type in the number to play. The links shouldnt be expired, they still play. It justs skips it/jumps:

steve@steve-Satellite-C655D:~$ cd Desktop
steve@steve-Satellite-C655D:~/Desktop$ rip-xiptv
enter a directory path: ~/Documents/schedule
 1) quit                68) ifceast
 2) 4seven              69) ioneast
 3) 5star               70) irishtv
 4) 5usa                71) itv
 5) abcfamily               72) itv2
 6) abcnews             73) itv3
 7) actionmaxeast           74) itv4
 8) a&eeast             75) itvbe
 9) alibi               76) itvencore
10) amc                 77) lifetimeeast
11) amceast             78) more4
12) animalplanet            79) movies24
13) bbc1                80) msnbc
14) bbc2                81) nationalgeowild
15) bbc4                82) nickelodeon
16) bbcamerica              83) nickjr
17) boomerang               84) ovation
18) cbsaction               85) oxygen
19) cbsdrama                86) pick
20) challenge               87) really
21) channel4                88) rt
22) channel5                89) documentary
23) chiller             90) rte2
24) cinemaxeast             91) rteone
25) cinemaxwest             92) sciencechannel
26) cinu                93) showtime2east
27) comedycentraleast           94) showtimebeyondeast
28) cookingchannel          95) showtimeeast
29) dave                96) showtimeextremeeast
30) destinationamerica          97) showtimenext
31) discoverychannelusa         98) showtimewest
32) discoveryfamily         99) skyaction&adventure
33) discoveryhistory           100) skyatlantic
34) discoveryturbo         101) skycrime&thriller
35) disneychanneleast          102) skydisney
36) disneyjr               103) skydrama
37) disneyxd               104) skyfamily
38) dmax               105) skymoderngreats
39) drama              106) skyone
40) dyinetworkusa          107) skypremiere
41) e!                 108) skyscfiandhorror
42) e4                 109) skyselect
43) eden               110) sonymovie
44) encoreactioneast           111) starcinemaeast
45) encoreeast             112) staredgeeast
46) encorewestern          113) starzkidsandfamilyeast
47) film4              114) starzwest
48) foodnetworkeast        115) syfy
49) fox                116) tbseast
50) fxeast             117) tcmus
51) fxxeast            118) teennick
52) gold               119) tg4
53) goodfood               120) themoviechanneleast
54) h2usa              121) themoviechannelextraeast
55) hallmarkmoviesandmystery   122) thrillermaxeast
56) hbo2               123) tlc
57) hbo2east               124) tnt
58) hbo2west               125) truedrama
59) hbocomedyeast          126) truemovie1
60) hbofamilyeast          127) truemovies2
61) hbo                128) trutveast
62) signature              129) tvland
63) hbosignatureeast           130) usanetworkeast
64) hbowest            131) watch
65) hgtveast               132) wetv
66) history            133) wgn
67) id                 134) yesterday

**Comment by steve55792** [comment]
by the way, i dont have it type like this in the folder or terminal, this is the way it looks when i paste it .

**Comment by NapoleonWils0n** [comment]
hi steve

i think the issue might be that the script uses ffplay and not mpv

I just changed the script to use mpv and not ffplay as the video player

do a git pull to update

and see if that resolves the issue

**Comment by steve55792** [comment]
how do  you do a git pull update? I'm having a duh moment. what the time over there? Here its 8pm.

**Comment by NapoleonWils0n** [comment]
hi steve

open terminal
- cd into git kodi-playercorefactory folder

```
cd ~/git/kodi-playercorefactory
```
- the do a git pull

```
git pull
```

**Comment by steve55792** [comment]
still does the same when ya choose a nuber to play with rip-xiptv

**Comment by steve55792** [comment]
here is what it says:   steve@steve-Satellite-C655D:~/Desktop$ pwd
/home/steve/Desktop
steve@steve-Satellite-C655D:~/Desktop$ rip-xiptv
enter a directory path: ~/Documents
1) quit        4) drama      7) hbowest       10) sky1
2) animalplanet    5) hbo        8) nickoledeon   11) sports
3) cbs         6) family         9) sky
Enter a number next to a video, or press '1' to quit: 11
Playing: /home/steve/Documentssports.txt
[file] Cannot open file '/home/steve/Documentssports.txt': No such file or directory
Failed to open /home/steve/Documentssports.txt.

and the saved urls are in folder document/schedule.

**Comment by NapoleonWils0n** [comment]
hi steve

from memory i think there might be an issue using the tilde when specifying a path

eg

 ~/steve/videos

try using the full path

eg

/home/steve/videos

see if that helps

**Comment by steve55792** [comment]
I forgot to add an / at the end of the folder. When I try to open some channels this what happens:

Enter a number next to a video, or press '1' to quit: 17
Playing: http://31.220.40.114:80/LiveEdge/BoomerangUS/chunklist_w2089020906_b1000000.m3u8?securehash=ZI97HyYpnCqiipMA3GyCamOtLdLw3cLpQzuchIglVAk%3D&securestarttime=1469008846&secureendtime=1469016046&secureuserid=fc6bd846a2bd5a4ee831624777cf21c7
[ffmpeg] http: No trailing CRLF found in HTTP header.
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ffmpeg] http: No trailing CRLF found in HTTP header.
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ffmpeg] http: No trailing CRLF found in HTTP header.
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ffmpeg] http: No trailing CRLF found in HTTP header.
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ffmpeg] http: No trailing CRLF found in HTTP header.
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
but it plays in kodi addon.

**Comment by NapoleonWils0n** [comment]
hi steve

is that when you are trying to record with ffmpeg you get that error with the rip-xiptv script

do the links record from kodi or on the command line with the rip-record script

sometimes you get ffmpeg errors with particular types of video streams

also some video links will work one player like mpv but not vlc or ffplay

**Comment by steve55792** [comment]
It doesn't play when I use the rip-xiptv in the terminal. And when I try the rip-record both in kodi and terminal it doesn't record, the size of the mkv file stays the same when trying to record

**Comment by steve55792** [comment]
It doesn't play when I use the rip-xiptv in the terminal. And when I try the rip-record both in kodi and terminal it doesn't record, the size of the mkv file stays the same when trying to record

**Comment by steve55792** [comment]
Record with ffmpeg???

**Comment by steve55792** [comment]
I cant schedule a at, it wont do anything even at a at now + 1 min
I even start with a sudo service atd start and i got my scheduler folder in the document folder

**Comment by steve55792** [comment]
but it will manually record in kodi like if you click on record/record 30 minutes

**Comment by steve55792** [comment]
actually i checked on the mkv file, it didnt record, it just saved the file.

**Comment by NapoleonWils0n** [comment]
hi steve

if it doesnt record from kodi or on the command line it wont work with rip-xiptv script or using at

you could try record manually with ffmpeg

eg save the url from kodi
replace video-url-goes-here with actual url inside single quotes
and save as an mp4

ffmpeg -i 'video-url-goes-here' -c:v copy -c:a copy out.mp4
