### ISSUE TITLE
video-link-checker

### ISSUE THREAD

**Issue by ElektrikSteve** [NapoleonWils0n/kodi-playercorefactory#25]
not recognizing renamed m3u links from m3u-pastebin-ripper
replying with no file found

**Comment by NapoleonWils0n** [comment]
hi 

does the script not work for you

you need to install the lynx browser, awk, sed and grep

i havent tested the script for a while so i do t know if the pastebin urls have changed

**Comment by ElektrikSteve** [comment]
Hi yes ive got everything in place all scripts work except that one. I'm
wondering if its when you changed the script m3u-link-checker. Have you
still got that somewhere i could give it a try

**Comment by ElektrikSteve** [comment]
I've done the latest git pull

And the only example I can find in you're vids is using a .txt file after
you changed the script

Think it might be something here as its not getting past the initial file
recognition

[[ -f "$FILE" ]] && find "$FILE" -maxdepth 1 -regex ".*.(txt|m3u)$"
-type f \

**Comment by ElektrikSteve** [comment]
Just checked on another machine. Same problem. Really enjoy the vids btw
good work my man

**Comment by NapoleonWils0n** [comment]
hi mate

i was thinking of the wrong script before

the video-link-checker script requires ffprobe

ffprobe is usually installed with ffmpeg if you are on linux

if your on mac or windows you will need to install ffprobe manually

the script is a bit basic and might not catch everything

whats your set up linux mac or windows

**Comment by ElektrikSteve** [comment]
Yes ive got all that as I said its not finding any file to process. What
ffprobe script can I manually put in the terminal. Im using Linux by the
way. Thinking if I run the instruction on an m3u file in the current
directory I can narrow down the problem

**Comment by NapoleonWils0n** [comment]
hi mate

what linux disto do you use out of interest

# script issue

it could be an issue with the script not finding the text file ad you said 
i seem to remember some glitch like that
- you could try putting the text file in a folder on the desktop

then try running the script and specifying the folder and then the text file 

then try cding into the folder and running the script again  and specify the text file

## ffprobe command

have a look at the script and ill try and explain how it works

line 9 of the script

what i do is run ffprobe on a link like so 

```
ffprobe -hide_banner http://example.com/video.mp4
```

and then check the exit status of the result of the ffprobe command

if the exit status is 0 that means the video link works and so the script echos the url and appends in to a text file

looking at the script i probably need to update the regular expression and check it works againist different url
as well as updating the way it finds text files

**Comment by ElektrikSteve** [comment]
I'll try the last script. Its not a single video file though its an m3u
with multiple links downloaded with pastebin ripper.

**Comment by ElektrikSteve** [comment]
The distro im using is peppermint. Its a cut down version of linux mint.
Not had any problems with your other scripts rip-play etc so i know that i
have it set up ok. And i have two laptops set up and all working fine apart
from this one script. Whats the -regex part of the script is that calling
the regex.sh script? Maybe its something there. All git pulls are up to
date. Can you send me the script for your original m3u-link-checker and
I'll run that and see whats happening

On 24 Jul 2016 00:42, "NapoleonWils0n" notifications@github.com wrote:

hi

does the script not work for you

you need to install the lynx browser, awk, sed and grep

i havent tested the script for a while so i do t know if the pastebin urls
have changed

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/NapoleonWils0n/kodi-playercorefactory/issues/25#issuecomment-234744989,
or mute the thread

**Comment by ElektrikSteve** [comment]
ok ffprobe working ok on single video file. That script wont work on an m3u
file though.

So there is a problem with it accessing m3u files

And maybe a problem with the syntax on the file search line
[[ -f "$FILE" ]] && find "$FILE" -maxdepth 1 -regex ".*.(txt|m3u)$"
-type f \

**Comment by NapoleonWils0n** [comment]
hi mate

the regular expression inthe video-link-checker is in the script and doesnt use the ripregex.sh file
- this is my linux tips git repo

https://github.com/NapoleonWils0n/cerberus
- old m3u link checker

https://github.com/NapoleonWils0n/cerberus/blob/master/kodi/old-scripts/bash-scripts-linux/m3u-link-checker

**Comment by NapoleonWils0n** [comment]
hi mate

maybe the regular expression in the script isnt catching the url

can you post the url and ill have a quick look

**Comment by ElektrikSteve** [comment]
Hi mate

the old script works fine, so something is not right in the new script.

Thanks

**Comment by ElektrikSteve** [comment]
Hi
so all working fine with the old script, so I'm trying to work a solution
out for the .ts live tv streams.
Im a noob on the coding front even though I did a HND in computer
engineering. It was over 20 years ago mind lol.
Anyway I've noticed if you run a ts file in ffplay it works fine for about
10 secs which is obviously the length of the current ts file. But if you
reload it, it works fine again.
Is there a way that you could set a loop up so that it re loads say every
so many seconds so if you get it close enough it will give you continuous
play.
Just an idea and probably you will say its not possible.
Ive watched your vid 29 on Curl and wget coding, fantastic stuff and I'm
about to go deeper into it all, but stop me if its a waste of time

Thanks again and keep up the good work

Steve

**Comment by NapoleonWils0n** [comment]
hi mate

video ts files are created by a media segmenter for use with m3u8 playlists

basically a video file or stream is chopped into 10 second chunks with .ts file extension
the files are usually in mpeg2 format like a dvd

the m3u8 playlist then contains links to the video.ts files which are usually in the same directory as the m3u8 playlist

the m3u8 playlist is updated in real time and new links to video.ts are added as they are created and old links are removed

 video.ts files arent worth bothering with, its the m3u8 playlist you want which links to the ts files

**Comment by ElektrikSteve** [comment]
Ok thanks for that. So if I monitor the network stream while running a ts
file with wireshark will that give me the m3u8 link ? People are getting
these ts files from somewhere or are they stripping the m3u8 section out to
get you to subscribe to their service And then giving you the full link ?

**Comment by NapoleonWils0n** [comment]
hi mate

have a look at videos 70 and 72 they show you how to find iptv links from Kodi using tcpdump or wireshark

you wont be able to find an m3u8 link ny playing a ts file, its the other way around

you find m3u8 playlist which link to ts files, then you can record the m3u8 playlist and it combines all the ts files into one video when you record

ts files on there own are useless they are just small chunks of the video.

so video ts files are just chunks from the video, you need the m3u8 playlist which has a list os all the video.ts segments that make up the video

so avoid ts files on their own you need the m3u8 playlist
have a look at videos 70 and 72 should make sense

**Comment by ElektrikSteve** [comment]
Ok will do thanks mate
