### ISSUE TITLE
scheduling with Vlc

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#28]
Is it possible to schedule vlc to record with the text url link that a person save from a live channel?
Like at 3pm tonight and schedule it to stop after a movie/tv show ends?

**Comment by NapoleonWils0n** [comment]
hi steve 

yes should be possible as long as vlc can play the url

you can use the at coomand to shcedule the record

have a look at the linux / vlc / playercorefactory.xml file

youll see some code to use with vlc to record

should be something like this

vlc your-url --stout=file/ts:"video.mp4"

but vlc can only play basic streams so would be better use ffmpeg

**Comment by NapoleonWils0n** [comment]
you cant set a duration for the recording with vlc
so you would have to create another at command to srop the record

to be honest would be easier to use ffmepg
