### ISSUE TITLE
recording

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#29]
Would it possible to record this channel:  http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts. It is one of the channel I would like to try to record, its one of my favourite channel.
Please let me know if you find away and do it.

**Comment by NapoleonWils0n** [comment]
Hi Steve

Good footie link
My team Newcastle United have been relegated to the Championship,
and the there seems to be a total media blackout on all the Championship games.
Not shown live or even on the radio. Very annoying

I forget what operating system you use

## Linux and Mac recording

```
ffmpeg -i 'http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts' -c:v copy -c:a copy "$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```

## Linux and Mac recording with duration
- record for 3 hours

```
ffmpeg -i 'http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts' -c:v copy -c:a copy -t 03:00:00 "$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```
- use the -t option to specify duration in hours, minutes, seconds
- 30 minutes 

```
-t 00:30:00
```
- 2 hours 

```
-t 02:00:00
```
- 3 hours 

```
-t 03:00:00
```

## schedule recordings with the at command on linux
- at read me page

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/docs/schedule-recordings

#### schedule recording and set 3 hour duration
- start the atd daemon before using at

```
sudo service atd start
```
- schedule record to start at 7.45 PM and record for 3 hours

```
at 7:45 PM
ffmpeg -i 'http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts' -c:v copy -c:a copy -t 03:00:00 "$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```
- Use ^d to exit from at prompt.

#### Some Notes
- the scripts dont work with .ts video urls
- mpv wont play that .ts link
- vlc and ffplay will play that .ts link
- ffmpeg can record .ts links

#### Windows notes
- If you are on Windows you will to change this part of the ffmpeg code from this

```
"$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```
- to this 

```
"$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```

##### Windows scheduling recordings

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/docs/schedule-recordings/windows-schedule-recordings.md

##### Mac  scheduling recordings

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/docs/schedule-recordings/mac-osx-at-command.md

**Comment by steve55792** [comment]
I tried with ffmpeg -i 'http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts' -c:v copy -c:a copy -t 00:30:00 "$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"  and it didnt work , this what happened after:

steve@steve-Satellite-C655D:~$ ffmpeg -i 'http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts' -c:v copy -c:a copy -t 00:30:00 "$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
  configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mpegts, from 'http://c0mmandpr0tv.ddns.me:8000/live/shtebo40/123456/2513.ts':
  Duration: N/A, start: 11751.544167, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 106 kb/s
[matroska @ 0x9668120] Codec for stream 0 does not use global headers but container format requires global headers
[matroska @ 0x9668120] Codec for stream 1 does not use global headers but container format requires global headers
[matroska @ 0x9668120] Error parsing AAC extradata, unable to determine samplerate.
Output #0, matroska, to '/home/steve/Desktop/video-2016-08-17-19-18-11.mkv':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p, 960x540 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 90k tbc
    Stream #0:1: Audio: aac ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, 106 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
steve@steve-Satellite-C655D:~$ 

Dont know if I'm missing files or not.

i

**Comment by NapoleonWils0n** [comment]
try recording as an mp4
otherwise youll have to google the error

**Comment by NapoleonWils0n** [comment]
you could also try setting the codecs to h264 for video and aac for audio

**Comment by steve55792** [comment]
how would you do that?

**Comment by NapoleonWils0n** [comment]
hi steve

change 

```
-c:v copy -c:a copy
```

to

```
-c:v libx264 -c:a aac
```

in the code

libx264 may be called something different like x264 on ubuntu

also check you have fdk-aac-dev installed
have a look at the git repo main page

also have a look at the rip record script which has different fixes for -c:v video codec and -c:a audio codec

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/bash-scripts/rip-record

**Comment by steve55792** [comment]
how do we get the bashrc file back, somehow its missing again, sorry.

**Comment by steve55792** [comment]
I re-installed the bashrc file and it showed up a blank bashrc file.

**Comment by NapoleonWils0n** [comment]
hi steve

ubuntu has a default bashrc you can copy

should be something like this

try this in the terminal

```
cp /etc/skel/.bashrc ~/.bashrc
```

you will then need to  add this code to the bottom of the ~/.bashrc in your home

```
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi
```

then source your bashrc file

type the following in the terminal

```
source ~/.bashrc
```

**Comment by steve55792** [comment]
when i source the bashrc file it turned out like this:
steve@steve-Satellite-C655D:~$ source ~/.bashrc
steve@steve-Satellite-C655D:~$

**Comment by steve55792** [comment]
I tried sudo apt install  fdk-aac-dev and it said cant find fdk-aac-dev. Maybe this is what causing all the issues

**Comment by steve55792** [comment]
By the way did windows 10 ever got their bash issue fixed? Maybe if they did ill try with Windows again.

**Comment by NapoleonWils0n** [comment]
hi steve

what version of ubuntu are you using

if you are using ubuntu mate the command is different

try running this in the terminal

```
sudo apt install fdkaac
```

**Comment by NapoleonWils0n** [comment]
hi steve 

when you source the bashrc you wont get any feedback in the terminal

thats normal

**Comment by NapoleonWils0n** [comment]
windows 10 still has the bug where it forgets the system path

also you cant schedule recordings with the at command on windows

**Comment by steve55792** [comment]
i  installed fdkaac with sudo apt install fdkaac and this what says after:
fdkaac is already the newest version (0.6.2-1).
The following packages were automatically installed and are no longer required:
  libpango1.0-0 linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic
  linux-headers-4.4.0-28 linux-headers-4.4.0-28-generic
  linux-image-4.4.0-21-generic linux-image-4.4.0-28-generic
  linux-image-extra-4.4.0-21-generic linux-image-extra-4.4.0-28-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.

do i have to remove the ones that are not required, would that be the issues im having with the program.

**Comment by steve55792** [comment]
I'm using ubuntu 16.04 LTS

**Comment by NapoleonWils0n** [comment]
hi steve

looks like you have some packages that can be upgraded

heres how to keep ubuntu up to date
- first you update like so

```
sudo apt update
```
- to upgrade packages you then run upgrade, like so

```
sudo apt upgrade
```

you should update and then upgrade regulary, eg every day
- it should be safe to autoremove unused packages, but always a good idea to back up to an external drive
- to autoremove packages, run the following command

```
sudo apt autoremove
```
- then reboot after autoremoving packages

not sure why you cant record the stream on ubuntu 
try updating and upgrading then reboot see if that helps
