### ISSUE TITLE
Video 51 of Yours

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#31]
Hi I was watching your video #51 about kodi checking iptv playlists for dead links with ffprobe and it looks pretty interesting, can you please explain to me a little more how to do cause Im interested but I am having a few blonde moments lately and I was trying to keep up with your videos but no luck

**Comment by NapoleonWils0n** [comment]
hi steve 

the script is called video-link-checker

just run the script and it prompts you to type in the path to a text file with video links in ( links on seperate lines )
then it creates a text file in the current directory called working links

**Comment by steve55792** [comment]
It didnt leave a directory called working links. Here what  i did:
steve@steve-Satellite-C655D:~/Desktop$ video-link-checker
enter the path to your text file: 2.txt
checking: http://globalstream.noip.us:8000/live/askin/askin/804.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/912.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/913.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/914.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/915.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/916.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/917.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/918.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/919.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/920.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/921.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/783.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/784.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/785.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/786.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/787.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/788.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/790.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/791.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/792.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/793.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/794.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/795.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/796.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/797.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/798.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/799.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/800.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/801.ts
checking: http://globalstream.noip.us:8000/live/askin/askin/802.ts
checking: https://iptv.zone ADULT=VOD20

**Comment by NapoleonWils0n** [comment]
it creates a text file not a directory

**Comment by steve55792** [comment]
it didnt create the text file either, at first i had the links in a folder called pastebin like you had in the folder but i took them all  and put thrm all on the desktop

**Comment by steve55792** [comment]
Okay, I got it working, but I only get to do one text file one at a time. What do you use to download the working links, wget?

**Comment by NapoleonWils0n** [comment]
yes you want wget

```
wget -i working-links
```

rtfm

man wget

q to quit

**Comment by steve55792** [comment]
how do you get the kodi-addon-pvr-iptvsimple client because i dont have it for my kodi

**Comment by NapoleonWils0n** [comment]
hi mate

```
sudo apt install kodi-pvr-iptvsimple
```

**Comment by steve55792** [comment]
thank you
