### ISSUE TITLE
arch linux

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#33]

**Comment by steve55792** [comment]
Is Arch Linux the same as Ubuntu cause I copied everything from the folders from Ubuntu to Arch folders and everything works like save url link but the record didnt work in  Kodi. Is it a different setup?

**Comment by NapoleonWils0n** [comment]
hi steve

arch and ubuntu are both linux, are different distrubutions

they have different package managers to install software

have a look at the main page of the kodi playercore factory github repo

there are instructions for installing everything on arch linux

you may need to install sed on arch

```
sudo pacman -S sed
```

have you set up the bashrc file and sourced it

check main page of the github repo for details

**Comment by steve55792** [comment]
all i did is just copied folders from ubuntu to arch linux so far, no I havent set up the bashrc file yet, is it different from ubuntu setup?, Im gonna to do it when I get home, I gotta go to my lovely job.

**Comment by NapoleonWils0n** [comment]
hi steve

its better to clone the git repo, 
set up the bashrc and copy the playercorefactory.xml into place on arch

rather than copying folders from ubuntu 
more likely to get errors

**Comment by steve55792** [comment]
the terminal says sudo pacman  not found, when i typed it in.

**Comment by NapoleonWils0n** [comment]
i cant do tech support
youll have to rtf

**Comment by NapoleonWils0n** [comment]
rtfm

**Comment by steve55792** [comment]
?

**Comment by NapoleonWils0n** [comment]
read the f*****\* manual

looks like you need to install sudo and add your self to the sudoers file

read the arch wiki about sudo

**Comment by steve55792** [comment]
Wow

**Comment by NapoleonWils0n** [comment]
rtfm is just an expression

dont mean it in a nasty way, 
just means you need to read the documentation

wasnt telling you to f off mate

so dont take it wrong way

install sudo

```
pacman -S sudo
```

then add yourself to sudoers file
read the arch wiki page

https://wiki.archlinux.org/index.php/sudo

use nano as sudoers editor

```
EDITOR=nano visudo
```

edit sudoers file

```
visudo
```

add your user to sudoers file

replace usrname with your username

```
USERNAME ALL=(ALL) ALL
```

save the file with nano

ctrl + o 

exit

ctrl  + x

**Comment by steve55792** [comment]
Lol, no problems, im just trying to figure out about linux/ubuntu, im  ex-windows person.

**Comment by NapoleonWils0n** [comment]
hi steve

have a read of the arch wiki page about sudo

1 basically you install sudo

2 set visudo to use nano as the editor

3 edit the sudoers file with visudo 

4 add your user to sudoers file

5 reboot

arch isnt very noob friendly but is a great OS

**Comment by NapoleonWils0n** [comment]
hi steve 

here how you switch to root on arch

```
su root
```

enter admin password

you should see the prompt now has a # in the terminal

something like this

```
root@yourmachine #
```

normally prompt looks likes this

```
steve@yourmachine
```

it wont have the name yourmachine thats just an example
it will be called whatever your machine is called

**Comment by steve55792** [comment]
I downloaded the file sudo 1.8.17.p1-1 [core](x86_64) pkg.tar.xz, how does a person install this?

**Comment by NapoleonWils0n** [comment]
Hi Steve

Generally you dont download the file manually you use the arch linux package manager which is called pacman ( short for package manager, not pacman the game )

1 - You need to switch to root to install sudo
- open the terminal and type the following to switch to root

```
su root
```

2 - Enter your root password ( admin password )

3 - Next you install sudo with pacman 

```
pacman -S sudo
```

4 - You have to edit the sudoers file and add your user so you can use sudo, it uses a special editor called visudo to edit the sudoers file

We are going to set visudo to use nano text editor to edit the sudoers file
- open the terminal and type the following to set visudo to use nano to edit the sudoers file

```
EDITOR=nano visudo
```

5  - edit the sudoers file by running visudo which will use the nano text editor to edit the sudoers file

open the terminal and run the following command, this will open the sudoers file with nano
it will prompt you for your root ( admin ) password

```
visudo
```

6 - you should see the section below in the sudoers file

```
##
## User privilege specification
##
root ALL=(ALL) ALL
```
- add the code below underneath the section that says root ALL=(ALL) ALL
  ( replace steve with the username you are using if needed )

```
steve   ALL=(ALL) ALL
```
- it should look like this

```
##
## User privilege specification
##
root ALL=(ALL) ALL
steve   ALL=(ALL) ALL
```

7 - save the file with nano by pressing control and o ( thats o and not zero )
and press return

8 - exit the file by pressing control and x

9 - reboot the machine

10 - you can now use the sudo command to install packages

Updating packages

to update the system and all packages you run the following command

```
sudo pacman -Syu
```

**Comment by steve55792** [comment]
i got it what i want it to do, thats great, that is to use the at recording but i use the instruction you sent last and i typed su root and type in the password, it says authorization failure.

**Comment by NapoleonWils0n** [comment]
hi steve
i didnt mean to confuse you

main thing is you have it working
heres the arch wiki page about sudo if you need it

https://wiki.archlinux.org/index.php/sudo

**Comment by NapoleonWils0n** [comment]
ill close this if everything is working
