### ISSUE TITLE
 MLB.tv  Recording 

### ISSUE THREAD

**Issue by Ibrahim2311** [NapoleonWils0n/kodi-playercorefactory#34]
Hi Mr Napoleon .

I'm apologizing if I did something wrong , I just need your help .
You're really a nice person , I'm just was confused that I won't finish my task before the deadline .

my account in Kodi Forum is banned since I tried to post 10 posts to unlock the pm message ,

So as you can see , I do have nothing to communicate with you now .
Please Can you help me with this .
it would be a life saver for me . 

thanks .

**Comment by NapoleonWils0n** [comment]
Hi Ibrahim

I closed the github issue by mistake whilst using my iPad
You didnt do anything wrong, just me being clumsy using the ipad

I just sent an email to the email address you left in a previous comment
I replied using my second youtube gmail address with the name Jack Griffin, so you know its me

Jack Griffin is the name i use to respond to comments on youtube

Do you want to reply to the email and send me the mlb.tv username and password

Then ill install the repo's zip file and login and have a look at the video

**Comment by Ibrahim2311** [comment]
Yes , thanks for you're  response , 
I've emailed you back with the login data .

**Comment by NapoleonWils0n** [comment]
Hi Ibrahim2311 

got the login details
installed the addon and added login details and opened a video stream and saved the url

just emailed you back

**Comment by Ibrahim2311** [comment]
Thanks for that , I've received it ,
and I replied as well ,

You're really nice and great person to know .

**Comment by NapoleonWils0n** [comment]
Hi Ibrahim

Eureka

i have managed to record from mlb.tv with ffmpeg 
and use ffplay and mpv as external players ( no vlc ) by adding new code to the scripts

I havent uploaded the new code to github yet

I need to create the mac and windows version of new code
Should be done later today, its 3am GMT ( night time ) now

So ill finish it off the code in the morning, should be ready in the afternoon GMT. 
In about 12 hours or so

Ill let you know when its ready and what you have to do to update

NapoleonWils0n

Just emailed you same message

**Comment by Ibrahim2311** [comment]
Thank you so much , you are the best sir .

**Comment by NapoleonWils0n** [comment]
Hi ibrahim

uploaded new code to github

just emailed you on how to update

you need to do a git pull see email for more info

**Comment by Ibrahim2311** [comment]
Thanks a lot Napoleon , I really appreciate your effort in this . 
hope I can return that favor back .

**Comment by Ibrahim2311** [comment]
Hi ,
I updated the script through (git pull) command , then
I've just tried it for a Yesterday fullgame match . and that what pops up (it flashes as the previous one)

![capture](https://cloud.githubusercontent.com/assets/21281149/18142047/81b6336e-6fc4-11e6-961a-235c10b0a443.PNG)

**Comment by NapoleonWils0n** [comment]
hi ibrahim

thats a windows error that goes back to windows 7

sometimes windows forgets whats in its system path

have a look at video 74 
bash command not found fix

basically you edit your windows system path and click ok and windows should remember where programs are installed
then open kodi and try again

have  look at video 74 and follow the steps to fix the issue

**Comment by Ibrahim2311** [comment]
I've applied that as well and it's now doesn't showing anything .
I've sent you an email that has a video to show you if I"m doing it right .

**Comment by Ibrahim2311** [comment]
OK I think it stopped recording everything .
let me check if there is something wrong I've done recently 

I've changed the (playercorefctory) file with the new one I guess in this directory :
C:\Users\Ibrahim\AppData\Roaming\Kodi\userdata

**Comment by NapoleonWils0n** [comment]
hi ibrahim

just emailed you

another fix to try

make sure you used the windows playercorefactory.xml file

**Comment by NapoleonWils0n** [comment]
hi ibrahim

you can try reinstalling cygwin 

just run the installer again

**Comment by NapoleonWils0n** [comment]
hi ibrahim

forgot to add a bit of code 

just uploaded new code to github

do a git pull to update like before

**Comment by Ibrahim2311** [comment]
Thanks a lot Napoleon , You are really great person .
Everything works properly , I'm thankful that you helped me .
