### ISSUE TITLE
Issue recording on addon DC Sports

### ISSUE THREAD

**Issue by robbo755** [NapoleonWils0n/kodi-playercorefactory#36]
Hi Napoleon

Further to my post.....

DC Sports is the add-on I am trying to record (seems to be all streams associated with this addon).  I have been successfully recording other live tv channels with no issues.

Using rasp pi on osmc.  Pressing y key then record but no output...

When I capture the url, this is the output:

http://163.172.170.33:8081/live/eurosport-hq/playlist.m3u8?wmsAuthSign=c2VydmVyX
3RpbWU9OS80LzIwMTYgNToyMzoxMyBBTSZoYXNoX3ZhbHVlPW9aSTczQ291NnpVZGY1aDhhWnlRRmc9PSZ2YWxpZG1pbnV0ZXM9NjAmaWQ9MTQxLjEwMS45OS44NSZzdHJtX2xlbj0xNw==|User-Agent=Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.
87 Safari/537.36

Running rip-record on this, produces a "Server returned 5XX" error.
Note the sed error always happens but I have had no issue recording up to now, so that appears to be an unrelated issue.

sed: -e expression #1, char 16: Invalid range end
[http @ 0x1dd5270] HTTP error 500 Internal Server Error
http://163.172.170.33:8081/live/eurosport-hq/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OS80LzIwMTYgNToyMzoxMyBBTSZoYXNoX3ZhbHVlPW9aSTczQ291NnpVZGY1aDhhWnlRRmc9PSZ2YWxpZG1pbnV0ZXM9NjAmaWQ9MTQxLjEwMS45OS44NSZzdHJtX2xlbj0xNw==|User-Agent=Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36: Server returned 5XX Server Error reply

If I run the regex-checker it returns HTTP.
I then get the corresponding grep condition from the video-regex.sh file and run that against the url, (outputting into test.txt) as follows:

grep -Eo '^(http|https)://[a-zA-Z0-9:0-9/.&;,~_?%@_=-]_' video-url-2016-09-04-15-23-30.txt > test.txt

If i then run rip-record test.txt, recording works!

Not sure why, as it appears I am just re-creating the steps the rip-record bash script does....

Hope you can help....

Thanks Robbo755

**Comment by NapoleonWils0n** [comment]
Hi robbo755

I have installed DC Sports ( nice addon for the Footy )
- seo-michael is a good place to check on how to install different repos

https://seo-michael.co.uk/how-to-install-dc-sports-kodi/

It actually matches the Wildcard regular expression using the regex-checker 
( the \* in the case statement )

You are right removing the User Agent works, 
and then i can run the rip-play and rip-record scripts and they work

Good detective work

Ill knock up a new regular expression to catch the url
Will take a little while as i have to update the following scripts
- regex-checker
- rip-play
- rip-play-mpv
- rip-play-vlc
- rip-record
- rip-ssh
- rip-stats
- rip-stream
- video-regex.sh

And then create the mac and windows versions as well

9 scripts x 3 operating systems = 37 scripts to update
And the commands for each OS are different

Have to see if i can tweak existing regular expression or create a new one

Give me a day or so and ill let you know when its ready
- I would also recommend NJM Soccer 

https://seo-michael.co.uk/tutorial-how-to-install-njm-soccer-kodi-xbmc/

**Comment by NapoleonWils0n** [comment]
Hi robbo755

DC Sports = Done
- Do a git pull to update

Recording and all external video players work
Managed to alter the M3U8USERAGENT regex in video-regex.sh to catch the url,
only had to add 4 characters

So i only had to update 3 scripts and not 37 scripts
Will add message to kodi forum as well

**Comment by robbo755** [comment]
Thanks for updating this.

Still seems to be a problem however:

rip-record video-url-2016-09-07-15-10-45.txt
sed: -e expression #1, char 24: Invalid range end
sed: -e expression #1, char 16: Invalid range end
http://163.172.150.10:8081/live/eurosport-hq/playlist.m3u8: Server returned 403 Forbidden (access denied)

URL is:
http://163.172.150.10:8081/live/eurosport-hq/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OS83LzIwMTYgNToxMDoyOSBBTSZoYXNoX3ZhbHVlPUFOc0luaFNnYkJQTjRXK2dvWlVmcnc9PSZ2YWxpZG1pbnV0ZXM9NjAmaWQ9MTQxLjEwMS45OS44NSZzdHJtX2xlbj0xNw==|UserAgent=Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

I did a git pull (and then double-checked).  I receive a message "Already up to date".  So I assume everything is ok with that.

**Comment by NapoleonWils0n** [comment]
Hi robbo

Have rejigged the code,
recording and external players are working

Strange i had it working before

Do a git pull to update
