### ISSUE TITLE
tcpdump

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#37]
Hi, Im trying using the tcpdump for extracting links from addon iptv playlists in your video #54  and when i put an  wlan0-06-45-09-04-16.pcap on the desktop it says 24 bytes and when I extract to a pcap-links-06-52-09-04-16.txt, it blank. I did what you did in Phoenix and Navi-x.

```
                                                                                    Thank You
                                                                                            steve
```

**Comment by NapoleonWils0n** [comment]
Hi Steve 

# tcpdump

check the name of your network interfaces

```
ifconfig
```

you can also try using the ip command

```
ip a
```

You wifi card may not be called wlan0
- replace wlan0 with the name of your network interface in the command below

```
sudo tcpdump -s 0 host 192.168.1.3 -i wlan0 -w wlan0-$(date +"%H-%M-%m-%d-%y").pcap
```

## Wireshark

Or you can use wireshark to do the same thing

dont run wireshark as root
add your user to wireshark group, replace username with your username

```
sudo gpasswd -a username wireshark
```
- Then reboot and you will be able to use wireshark without using root
- Have a look at the Wireshark video, should show you how to do the same thing but with a gui

https://www.youtube.com/watch?v=6aojXDxKdAw

**Comment by steve55792** [comment]
this is what i got:1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:26:6c:ca:34:a8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.99/24 brd 192.168.0.255 scope global dynamic eth0
       valid_lft 85290sec preferred_lft 85290sec
    inet6 fe80::226:6cff:feca:34a8/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e0:ca:94:11:f2:6e brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.80/24 brd 192.168.0.255 scope global dynamic wlan0
       valid_lft 76317sec preferred_lft 76317sec
    inet6 fe80::e2ca:94ff:fe11:f26e/64 scope link 
       valid_lft forever preferred_lft forever
Im guessing its number 2?

**Comment by NapoleonWils0n** [comment]
HI Steve 
Looks like you have 2 network interfaces

Number 2: eth0
Number 3: wlan0

They both have ip addresses so they look like they may both be active
You could click on the wifi icon at the top of the screen and turn it off temporally

And then try running the command with eth0 instead of wlan0

You can also use wireshark and select the network interface and then select capture
Then stop it when you are finished, and then save the file as capture.pcap to your desktop

**Comment by steve55792** [comment]
the first thing didnt work, dont know why and i switched it to eth0. Ive tried wireshark and it said permission denied? Is there away to switch it over? I mean to get permission.

**Comment by NapoleonWils0n** [comment]
Hi Steve 

You need to add yourself to the wireshark group and that will fix the permission denied error

add your user to wireshark group, 
replace username with your username

```
sudo gpasswd -a username wireshark
```
- Then reboot

Open up wireshark again and select eth0 and then click start and it will start the capture
- When wireshark is running you can filter the traffic to just http connections by typing http in the text box marked filter

**Comment by steve55792** [comment]
I got in a group in wireshark but it still says needing permission for eth0. I wish windows get their bash script working.

**Comment by NapoleonWils0n** [comment]
hi steve

thought you were using linux

if you are using window you need windump

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/docs/windump/windump.md

i made videos about installing wireshark and windump on windows
youll need to watch the video and look at the read me

not a windows user, cant do windows tech support

**Comment by steve55792** [comment]
Lol,  im still using arch linux but still have windows 10 on the computer  but wishing windows 10  fix the bash script issue they have .

**Comment by steve55792** [comment]
so i use your program in windows.
