### ISSUE TITLE
Xbmc MyLibrary 1.43

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#41]
Would using Xbmc MyLibrary 1.43 scanning all the files  automatically to a folder with your program  to rip-record the movies/episodes work?

**Comment by NapoleonWils0n** [comment]
hi steve

i havent used that addon before
i would have thought that if you are just importing the links they should be the same 

so it might work, only one way to find out install the addon and give it a go

**Comment by steve55792** [comment]
actually i think that addon is not working anymore(what i read in the forum)but another one to try is pseudolibrary that creates the same strm files as the other addon, it will be cool if it did work with your program, Im gonna give it a shot and see if it works.

**Comment by NapoleonWils0n** [comment]
hi steve

 i have used pseduo library before

and it lets you add movies and tv shows to your library by creating .strm files

the links are just the same as normal kodi links or links you put in a m3u8 playlist

so should work in theory

**Comment by steve55792** [comment]
Hi NapoleonWilson

I looked at one of the strm link I got and its pretty long file. Here's one of the links: 
plugin://plugin.video.pseudo.library/?url=plugin%3A%2F%2Fplugin.video.dahenchmen%2F%3Furl%3Dhttp%253A%252F%252Fdahenchmen.xyz%252F01%252FD4Henchm3n%252Fm0v13z%252Fboxs%252Fpurge.xml%26mode%3D3%26name%3DThe%2BPurge%253A%2BAnarchy%26description%3D%26fanart%3Dx&mode=10&name=The+Purge+Anarchy&fanart=image%3A%2F%2Fx%2F. 

How would a person use that link to rip-record with your program?

**Comment by NapoleonWils0n** [comment]
hi steve

those are plugin links not actual urls  - so you cant record the url in the strm file

you need to open that link in kodi which should open the url
then you can press y on the keyboard and try recording playing or saving the link

**Comment by steve55792** [comment]
when recording is there another format besides .mkv that the files can be like mpg?

**Comment by NapoleonWils0n** [comment]
hi steve

it depends on the video stream codecs you are trying to record what you can save it as
you can save pretty much anything into an mkv

**Comment by steve55792** [comment]
i'm sorry i mean if i can save the video as like an mpg file instead of an .mkv file?

**Comment by NapoleonWils0n** [comment]
hi steve

mpg files can usually only contain mpeg2 encoded video stream

so depends on the video codec used in the stream

**Comment by steve55792** [comment]
thank you

**Comment by NapoleonWils0n** [comment]
hi steve

no problem

generally mkv is the best option
