### ISSUE TITLE
Issue with latest version of playercorefactory

### ISSUE THREAD

**Issue by robbo755** [NapoleonWils0n/kodi-playercorefactory#42]
Hi Napoleon

Having a few interesting issues since the last update.  When recording a live stream (rip-record), I get a message that the option reconnect is not found:

url matches: $rtmp bash pattern
Recording: 'rtmpe://94.102.49.194/live?wmsAuthSign=c2VydmVyX3RpbWU9MTAvOS8yMDE2IDE6MDU6MzUgQU0maGFzaF92YWx1ZT1ERGJ5T1pZekx1K1kwZHBxYzFlWnJ3PT0mdmFsaWRtaW51dGVzPTEw playpath=qvWQUv36A0_4165 swfUrl=http://cast4u.tv/jwplayer/jwplayer.flash.swf token=%XB00(nKH@#. flashver=WIN\2023,0,0,162 live=1 timeout=15 pageUrl=http://www.cast4u.tv/embed.php?v=skys3&vw=700&vh=480'
Option reconnect not found.

No recording occurs.

However, when recording a different live stream (with a bash pattern of m3u8token) recording does occur.

I am using OSMC (Debian) on a rasp pi 3.

Cheers
Robbo

**Comment by NapoleonWils0n** [comment]
Hi robbo

the new code is used to reconnect and resume recordings if the streams connection drops out

another user had the same issue on the mac
they werent using the version of ffmpeg i had recommend on the mac

they fixed the problem by installing the correct version

im on arch linux using the latest version of ffmpeg 3.1.4
so should be the same on all recent linux distros

perhaps the version of ffmpeg on osmc with debian is rather old

2 solutions

 1 -  see if there is another version of ffmpeg in the osmc debian repo ( have you tried back ports ? )

2  - fork the git repository and remove the reconnect code

**Comment by NapoleonWils0n** [comment]
hi robbo

let me know how you get on

if there isnt another version of ffmpeg on osmc best to for the git repo and remove the reconnect code

i can always give other osmc users a heads up and put a link to your osmc version on the github read me page

cheers

**Comment by NapoleonWils0n** [comment]
hi robbo 

second thoughts

if need be i can create a linux version without the ffmpeg reconect code

but let me know if you can find another version of ffmpeg first that works

**Comment by robbo755** [comment]
hi napoleon

i checked my version of ffmpeg and can see the **http** protocol is enabled (as per ffmpeg documentation section 25.11 this is where the reconnect parameters reside).  I did enable backports to install ffmpeg initially when i started using playercorefactory.

so thought i would test a bit further...

tried another couple of sites and when using the **http** bash pattern, recording works fine.
as per initial e-mail already tested on **m3u8token** and that works
checked bbc iplayer (**m3u8**) and that works

so it appears the problem lies with the specific ffmpeg call for the rtmp bash pattern.....

the site that is not working is filmon.tv (bbc1) which I am using to test the rtmp case.

I've had a close look at the ffmpeg call in rip-record but can't see anything out of sorts.  It is doing something with rtmpdump, not sure if this is a factor and this is causing the parameter calls to ffmpeg to do something strange.

**Comment by NapoleonWils0n** [comment]
hi robbo

so just an issue with filmon and rtmpdump withe the ffmepg reconnect code

i was pipping rtmp into ffmepg 

ill change the rtmpdump code and remove the ffmepg connect code from rtmp

will sort it this afternoon and push the changed to github

ill post a comment here when its ready

good catch mate

**Comment by NapoleonWils0n** [comment]
hi robbo

remove reconnect ffmpeg code from rtmp

do a git pull to update

and let me know if it resolves the issue

cheers

**Comment by robbo755** [comment]
works again mate, thanks for your help
