### ISSUE TITLE
Android Device

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#43]
HI NapoleonWilson, how hard would it be to put linux and your program on an android? I think you mentioned something in your videos about it, but not sure.

**Comment by NapoleonWils0n** [comment]
hi mate

i did try to get the scripts to work on android but didnt have any joy

problems finding ffmpeg version for android and installing the necessary tools like sed and grep

also i dont have any android devices to do any testing on and i couldnt get a virtual machine running android to work

cheap alternative is to use a rasperberry pi for recording instead
you can use my rip-ssh script to send the url from kodi and ffmpeg commands over ssh to record on thepi

**Comment by steve55792** [comment]
Is it possible to stream from my laptop to my android device after recording, i think you mention in one of the videos using ssh i think.

**Comment by NapoleonWils0n** [comment]
hi steve

the script you want is called rip-stream

have a look at video 40

kodi stream to multiple machines at once

**Comment by NapoleonWils0n** [comment]
hi steve

also look at video 41

set a duration for the stream

**Comment by steve55792** [comment]
Thank you
