### ISSUE TITLE
Cant record from at.

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#44]
Hi, I switched to Ubuntu Mate and I cant record from the terminal with at but I can record inside Kodi.
Was there anything updated on your program?

**Comment by NapoleonWils0n** [comment]
Hi Steve

Ubuntu Mate has different names for some of the packages

have a look on the page below at the ubuntu mate install commands

https://github.com/NapoleonWils0n/kodi-playercorefactory

see if that resolves the issue

**Comment by NapoleonWils0n** [comment]
hi steve 

didnt see your where having a problem with at command to schedule recordings

have you enabled the at daemon

not sure is ubuntu mate uses systemd or not

the systemd commands are
- to enable the at command which will load it every time you login

sudo systemctl enable atd
- to start the at command

sudo systemctl start atd

if it doesnt use systemd you should use service instead

sudo service atd start

you may need to do a little googling about how to enable the at commnad on ubuntu mate

i havent really used ubuntu mate but i know some of the package names are slighty different from ubuntu

**Comment by steve55792** [comment]
either ones of the daemon not sure if it worked or not but when i try use one of the rip-play or rip-record, it says command not found. and i did everything correct from the documentation

**Comment by NapoleonWils0n** [comment]
hi steve

you can check if you using systemd by checking if systemctl is installed

run the following command

whereis systemctl

that should show you where its installed

1- do you have a git folder in your home
2 - have hou download the git repo into the git folder
3 - did you edit your bashrc and add the path to the scripts

**Comment by NapoleonWils0n** [comment]
hi steve

and remember to source your bashrc as well

**Comment by steve55792** [comment]
Hi,
The systemctl is: systemctl: /bin/systemctl /usr/share/man/man1/systemctl.1.gz
1. Yes i have a git folder in my home.
2. the git repo, you mean the kodi playercorefactory.xml in the git folder?
3. yes, I edit the bashrc with  and the path to scripts

**Comment by NapoleonWils0n** [comment]
hi steve

you should have a git folder in your home
and inside it a folder called kodi-playercorefactory

can you use the rip-record script on the command line

is it just not working using the at command

have check the at command daemon is actaully running

try running this to create a text file

at now + 1 min
touch ~/Desktop/at-test.txt

ctrl d to exit at command 

that should create a text file on the desktop

**Comment by steve55792** [comment]
the rip-record doesnt work either and the at now + 1 min
touch ~/Desktop/at-test.txt worked, it created a text file.

**Comment by NapoleonWils0n** [comment]
hi steve

do you mean it cant find the rip-record script

or that it can find the script but it doesnt work

check your bash path

echo $PATH

either you dont have the scripts in the right location or you have a typo in your bashrc

or you havent installed the programs for ubuntu mate

**Comment by steve55792** [comment]
this what echo $PATH gave me: steve@steve-Satellite-C655D:~$ echo $PATH
/home/steve/bin:/home/steve/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
steve@steve-Satellite-C655D:~$ 

the scripts in the home folder  and i moved the bashrc to the desktop and try doing a new bashrc but the new one gave me a blank bashrc script so i put the old bashrc back and deleted the other bashrc. Havent installed the programs for ubuntu mate?

**Comment by NapoleonWils0n** [comment]
hi steve

the scripts arent in your bash path 

thats why its not working

have a look at the front page of the git repo

follow step 1 and install the programs where its says ubuntu mate install

follow step 4 and add the code to your bashrc and then source it

**Comment by NapoleonWils0n** [comment]
hi steve

i did check the scripts work on ubuntu mate using bashrc when i wrote the read me

i dont think ubuntu mate has stopped using bashrc

have a google on the version of ubuntu mate you are using and using the bashrc to add scripts to your bash path
