### ISSUE TITLE
rip-record

### ISSUE THREAD

**Issue by ElektrikSteve** [NapoleonWils0n/kodi-playercorefactory#46]
Hi Im trying to change the download file location  in the rip-record script to my windows partitition where there is more space. I can access it and copy files in the linux terminal but when I change the script it wont work.
my path is /media/srf/D896FB8C96FB6A00/FILMS/. Tried everything but no success. 
Everything else works fine

**Comment by NapoleonWils0n** [comment]
Hi ElektrikSteve 

Are you using linux or Windows

If you want to edit the scripts it best to fork the kodi-playercorefactory git repository,
otherwise you changes will get overwritten when you do a git pull

## fork the git repo

https://help.github.com/articles/fork-a-repo/

Keep the same name "kodi-playercorefactory" for the git repo

So it should look something like this

https://github.com/ElektrikSteve/kodi-playercorefactory

* Then rename the "kodi-playercorefactory" folder in your home/git to "kodi-playercorefactory-old"

* After that you need to clone your kodi-playercorefactory fork to your home/git folder

```
/home/username/git/kodi-playercorefactory
```

## changing the recording location

You need to search for "recordingfile" in rip-record and change the file path in every instance

Linux:

```
recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
```

Windows:

```
recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```

## recordingfile location

```
recordingfile="/media/srf/D896FB8C96FB6A00/FILMS/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```

And push your changes back up to github

**Comment by ElektrikSteve** [comment]
Yeh done all that

**Comment by ElektrikSteve** [comment]
I'm on Linux

**Comment by ElektrikSteve** [comment]
I did a search and replace of all instances. I think it's to do with
scripting to another partition but not sure

**Comment by NapoleonWils0n** [comment]
Hi ElektrikSteve 

You need to start here and change 

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/bash-scripts/rip-record#L122

and change this 

```
recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
```

to this

```
recordingfile="/media/srf/D896FB8C96FB6A00/FILMS/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
```

**Comment by NapoleonWils0n** [comment]
Hi ElektrikSteve

maybe its something to do with the mount name

**Comment by t3rmin8tor** [comment]
i would guess that  if the partition you are trying to write to is a windows 10 parition  and the script is trying to access a drive it does not have authority to write to  ......... where as  accessing the windows partition from the terminal  as a user or SU or root will allow the access and write permissions  it all depends on what access levels the scripts have

**Comment by ElektrikSteve** [comment]
Well it works in a terminal but not in the script. Have you saved to a
different partition successfully?

**Comment by ElektrikSteve** [comment]
It saves to my desktop OK. I've got it set up on windows too but I can't
get it to work at all lol it's a pain in the ass on windows. Prefer Linux
but only got a small partition for it so it runs out of space quickly

**Comment by NapoleonWils0n** [comment]
Hi ElektrikSteve

Have you tried adding the mount to fstab

i mount my nfs share on a nas to the video folder in my home using fstab

**Comment by ElektrikSteve** [comment]
I've copied files without sudo in the terminal no problem

**Comment by ElektrikSteve** [comment]
No I haven't think I might have to. I thought a simple change of location
in the script would have done it but I don't think it likes accessing other
partitions

**Comment by ElektrikSteve** [comment]
The partition is NTFS windows 8.1

**Comment by t3rmin8tor** [comment]
even as a user  you have a higher permission level than a script will  it could simply be  a case of chown the scripts  or chmod

**Comment by NapoleonWils0n** [comment]
HI Mate

Do you have ntfs-3g installed, 
which might be needed to write to ntfs drives

You can search for ntfs packages using apt-cache search

i think the command is 

```
apt-cache search ntfs
```

* i think the newer command is

```
apt search ntfs
```

**Comment by NapoleonWils0n** [comment]
Hi Mate

Have you tried to save to an linux formatted external drive
then you'll know the problem is writing to ntfs drives

**Comment by ElektrikSteve** [comment]
Yes once I get it working I probably will but as it is it's at default level

**Comment by ElektrikSteve** [comment]
Is that just for scripts as I can copy files easy using the terminal so no
problems with access.

HI Mate

Do you have ntfs-3g installed,
which might be needed to write to ntfs drives

You can search for ntfs packages using apt-cache search

i think the command is

apt-cache search ntfs


   - i think the newer command is

apt search ntfs
.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Can you copy files to the ntfs drive using the file manager and not the command line

What linux distro are you using

**Comment by ElektrikSteve** [comment]
Yes copy with file manager Mint 18 cinnamon 32 bit

**Comment by NapoleonWils0n** [comment]
Hi Mate

Have you changed all occurrences of recordingfile in rip-record

```
recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
```

can you post the code you have changed

**Comment by NapoleonWils0n** [comment]
Hi Mate 

Have you tried changing the permissions on the scripts using chown

```
chown $USER -R ~/git/kodi-playercorefactory/bash-scripts
```

**Comment by ElektrikSteve** [comment]
Hi mate
Will run through those tomorrow and get back to you. Got early start
tomorrow
Thanks for your help so far

**Comment by NapoleonWils0n** [comment]
HI Mate

No worries
Hope one of them works
