### ISSUE TITLE
Installing Kodi 17

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#47]
Hi, Would you know how to upgrade 16.1 Jarvis to Kodi 17 Krypton? I tried  a couple ways to do it but no luck upgrading kodi to 17 in Ubuntu Mate. 
                                                                           Thanks
                                                                               Steve

**Comment by NapoleonWils0n** [comment]
Hi steve55792

Kodi 17 wont be in the main repo's for Ubuntu Mate yet as its still in Beta
I'd hold off trying to upgrade as there are couple of addons that arent working in Kodi 17

I run Debian unstable branch on a Mac Air so im running Kodi 17 on Debian,
on my other Mac air running Arch im still running Kodi 16.1

Id hold off until its ready to be honest

I made a video previewing Kodi 17 here:

https://www.youtube.com/watch?v=0CbAx5bBRQg

In Kodi 17 you have to enable unknown sources to let you install addons from external repos
