### ISSUE TITLE
cant download this link or play other than kodi player

### ISSUE THREAD

**Issue by ElektrikSteve** [NapoleonWils0n/kodi-playercorefactory#49]
cant play or download this link its in XvBMC Troma

https://r8---sn-8pgbpohxqp5-auol.googlevideo.com/videoplayback?ipbits=0&mn=sn-8pgbpohxqp5-auol&mm=31&requiressl=yes&signature=8DA01108973D9595E60C9D1D0AF608B1D5DEDB29.0FE4FD5B9600D2EFBAFCB4174FBDD007ACA00DC5&expire=1481170158&ms=au&mv=m&mt=1481148437&dur=5122.530&lmt=1403063644668734&ip=82.44.54.136&key=yt6&id=o-AA3N2nLwFujGOgqL1coh-Izeqa7bbmQDeZJFNi3AxXAR&itag=18&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=Kv50Q_9XDOg&mime=video%2Fmp4&pcm2cms=yes&ratebypass=yes&pl=21&source=youtube&initcwndbps=2211250|User-Agent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A10.0%29+Gecko%2F20150101+Firefox%2F47.0+%28Chrome%29

I saved URL to desktop. This is the result. Any ideas ?

**Comment by NapoleonWils0n** [comment]
hi mate

its google video link with a user agent

i can confirm the scripts arent catching the url
it should be possible to tweak the scrips to catch it

just setting up new site for tech support

i have saved the url
and will put it on my todo list

**Comment by ElektrikSteve** [comment]
OK keep up the good work 😎

On 7 Dec 2016 22:33, "NapoleonWils0n" <notifications@github.com> wrote:

hi mate

its google video link with a user agent

i can confirm the scripts arent catching the url
it should be possible to tweak the scrips to catch it

just setting up new site for tech support

i have saved the url
and will put it on my todo list

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NapoleonWils0n/kodi-playercorefactory/issues/49#issuecomment-265595012>,
or mute the thread
