### ISSUE TITLE
downgrading

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#50]
How do we downgrade from kodi 18 back to kodi 16.1 cause kodi 18 sucks and lags bad , sorry about the language

                                                                              Thanks
                                                                             steve

**Comment by NapoleonWils0n** [comment]
HI Mate

Thought you were a bit brave running Kodi 18

You could try running the following to purge kodi

```
sudo apt purge kodi*
```

Then autoremove unused packages

```
sudo apt-get autoremove
```

Then search for kodi

```
apt search kodi
```

And install Kodi

```
sudo apt install kodi
```

I would have thought that you should have Kodi 16.1 in the main repo for ubuntu mate
unless you have upgraded mate to a bleeding edge version

**Comment by steve55792** [comment]
I dont think i upgraded mate to a edge versioin? the main repo wont let me install for ubuntu mate it says i dont have permission to install kodi to ubuntu. Weird??????? When i reinstalled kodi yesterday that is what version it gave me.

**Comment by NapoleonWils0n** [comment]
Hi Mate

You can check which version of mate you are using by running this command

```
lsb_release -a
```

I installed Ubuntu Mate 16.10 in a virtual machine about 1 week ago and it installed Kodi 16.1

Im running Debian unstable branch on 1 machine, which means i get the latest version
and im only running Kodi 17 on that 

So dont know why its trying to install Kodi 18

**Comment by steve55792** [comment]
this is what it says: No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
So Im confused also about why its trying to install kodi 18. So im going to do what you told me to do above and see if it install kodi 16.1

**Comment by steve55792** [comment]
Hmmmmmm, It reinstalled kodi 18 again. When i retry with the welcome center to reinstall kodi  and it says i dont have the privileges to form this action. and the details says: 
org.freedesktop.PolicyKit.Error.Failed: ('system-bus-name', {'name': ':1.7162'}): org.debian.apt.install-or-remove-packages

**Comment by NapoleonWils0n** [comment]
Hi Mate

Are you using the software center or the command line to try and install Kodi

Dont use the software center to install programs,
use the command line will cause you less grief

Try unistalling Kodi again
You could try running the following to purge kodi

```
sudo apt purge kodi*
```

Then autoremove unused packages

```
sudo apt-get autoremove
```

Then search for kodi and see what version it shows

```
apt search kodi
```

**Comment by steve55792** [comment]
i did an apt search kodi and here is a file of what it said(would be a long list if i copy and paste way):
[new file.txt](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/639967/new.file.txt)

**Comment by NapoleonWils0n** [comment]
Hi Mate

You seem to have some Kodi 18 config files left,
which may be why its trying to reinstall Kodi 18

We need to remove those files and hopefully it will resolve the issue

* Looking at this page 

https://help.ubuntu.com/community/AptGet/Howto#Removal_commands

It recommends running these commands

Try running these commands one after another

* purge kodi

```
sudo apt-get purge kodi
```

* autoremove kodi

```
sudo apt-get autoremove kodi
```

* remove all configuration data from every removed package with the following command

```
dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge
```

* Then run a apt-get update

```
sudo apt-get update
```

* Then search for kodi using apt and check which version it shows you

```
apt search kodi
```

See if that helps

**Comment by steve55792** [comment]
i get a :dpkg: error: requested operation requires superuser privilege
steve46@steve46-EB1007P:~$ dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge

**Comment by NapoleonWils0n** [comment]
Hi Mate

try running it with sudo 

```
sudo dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge
```

**Comment by steve55792** [comment]
even with sudo, it gives the same error

**Comment by NapoleonWils0n** [comment]
Hi Mate

* just did a quick search, try this and see if it works

```
sudo -i dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge
```

**Comment by steve55792** [comment]
no luck same error. maybe i should reinstall ubuntu mate to see if that helps.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Yes might be easiest fix for you
Do a reinstall of Ubuntu Mate 16.10, doesnt take long to install

**Comment by steve55792** [comment]
any luck it might work, frustrating huh? im gonna try it. ill let ya know the outcome, thanks for the help.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Ubuntu Mate 16.10 will install Kodi 16.1,
and all the scripts work i tested on a virtual machine about 1 week ago

Not sure why the fixes didnt work,
best to do a fresh install and that will fix the issue

Ill close this issue,
let me know if a reinstall works

**Comment by steve55792** [comment]
Reinstall ubuntu mate and kodi 16 is installed, maybe something in ubuntu had an error.  Now i have to reinstall your program, it'll be worth it. How is the Gui App coming along with your new forum?

**Comment by NapoleonWils0n** [comment]
Hi Mate

* Windows Beta installer

https://github.com/t3rmin8tor/kodi-player-core-factory-install

* Download

http://rip-record.duneasy.co.uk/download

* New site

http://rip-record.duneasy.co.uk

* Tutorials

http://rip-record.duneasy.co.uk/tutorials


Still building the new site so need to add forum for tech support and other stuff

**Comment by NapoleonWils0n** [comment]
HI Mate

The t3rmin8tor is also working on a GUI linux installer as well

**Comment by steve55792** [comment]
cool cant wait to see how it works
