### ISSUE TITLE
Youtube Error

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#52]
Hi , 
Im not sure if you use Youtube  in Kodi on Ubuntu Mate but every time i try to use Youtube in Kodi, I get an error to check log for information. One thing weird is that happens with any build in Kodi but it works fine when a person does a refresh of Kodi. Here is my Log(Hope I picked the right one?):
[kodi.txt](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/645806/kodi.txt)

                                                                                                                Thank You
                                                                                                                      Steve

**Comment by NapoleonWils0n** [comment]
Hi mate

i dont really use the kodi youtube addon to be honest

so not sure why its not working
did you install youtube from the main kodi repo


i would use youtube-dl to download youtube videos,
it can also download playlists and entire channels

you can also use mpv to play videos from youtube as well
and it cuts out all the ads
