### ISSUE TITLE
Kodi-automation

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#54]
What is this script all about? I read the information, how does it work? The Kodi-automation that is.

**Comment by NapoleonWils0n** [comment]
HI Mate
Just dev code to check if kodi is open and if not open kodi
not going to be used for anything

**Comment by steve55792** [comment]
oh okay, but did sound cool

**Comment by NapoleonWils0n** [comment]
HI Mate

was just helping another user called sirprancelot with some dev code

* he has a guide for setting up a raspberry pi with ffmpeg and all the scripts

https://github.com/sirprancelot/pi-video-recorder

**Comment by steve55792** [comment]
isnt it similar like your program

**Comment by steve55792** [comment]
his bash script for rip-record remote is interesting.

**Comment by NapoleonWils0n** [comment]
H Mate

yes same thing,
he just forked the repo and made some tweaks

and wrote set up guide for the pi

**Comment by steve55792** [comment]
what wiuld be interesting if someone can forked the repo into a tv schedule EPG like schedule where you click on the episode or movie and it automatically write it out for you, no matter what the schedule date or time is for the show or movie runs.
