### ISSUE TITLE
Failing to record from TuneIn Radio

### ISSUE THREAD

**Issue by robbo755** [NapoleonWils0n/kodi-playercorefactory#56]
Hi Napoleon

Now I know this is not video :)

I have been successfully recording from TuneIn Radio (by setting the value "audio" to true in playercorefactory.xml for the relevant menu options).

However recording (using rip-record either directly from playercorefactory or the command line) has stopped working with the following error:
url matches: $refuseragent bash pattern
Recording: 'http://moon.wavestreamer.com:7196'
[tcp @ 0x5603e380] Port missing in uri
http://moon.wavestreamer.com:: Invalid argument
[tcp @ 0x56a7b380] Port missing in uri
http://moon.wavestreamer.com:: Invalid argument
[tcp @ 0x5592d380] Port missing in uri
http://moon.wavestreamer.com:: Invalid argument

any ideas?

cheers
Robbo

**Comment by NapoleonWils0n** [comment]
hi robbo

dont worry that its not video
have been thinking should cover recording audio as well

eg: rip-audio script

will need to save the urls from tunein and other kodi audio addons
so i can look at the url structure and create the regular expressions to match the urls
then create the ffmpeg commands to record the audio

so the plan is to copy the rip-record script to rip-audio

then change the regular expressions to match tunein links and other audio addons,
and change the ffmpeg commands to record just audio 

so i need to create a collection of the different kinds used by kodi audio addons
and the regular expressions to match them
