### ISSUE TITLE
How to automate video-link-checker?

### ISSUE THREAD

**Issue by gabriellluz** [NapoleonWils0n/kodi-playercorefactory#57]
Hi. Now I've just used your installer and everything works great.

I have a ambitious project and I'd like make video-link-checker actually read my specific m3u8 file without typing. I want to use it like a bat file, automatically. Any help???

**Comment by NapoleonWils0n** [comment]
HI gabriellluz 

Hope the installer was easier to use than manually installing everything

* I need to improve the video-link-checker so it doesnt check images as well

## checking m3u8 files automatically

You could check a folder for m3u8 files or a specific m3u8 file and run the video-link-checker script

### On linux

Using linux you could use the watch command to monitor a folder and if new m3u8 files are added check them using the video-link-checker script

Or you could use cron to schedule the video-link-checker script to run every day, or every x number of hours and check a folder or m3u8 file 

### Windows

Windows doesnt have a watch command or cron

The only thing that you could use on windows is schtasks to schedule the video-link-checker to run every day, or every x number of hours 

But im not a Windows user and dont have a clue on how to use schtasks

I know how to write bash scripts that work on Windows but not bat files

Possible to auto check m3u8 files on linux using watch or cron, but you need to use schtasks on windows which i dont know how to use

### 2 options

* get a raspberry pi and use linux to check your m3u8 files
* use windows and read up on schtasks

* schtask links

http://www.howtogeek.com/123393/how-to-automatically-run-programs-and-set-reminders-with-the-windows-task-scheduler/

https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx

http://ss64.com/nt/schtasks.html
