### ISSUE TITLE
Problems with ITV Player

### ISSUE THREAD

**Issue by chrisinodentino** [NapoleonWils0n/kodi-playercorefactory#58]
Hi. Thanks for this awesome way of capturing streams. BBC Iplayer and UKTV work flawlessly but I get issues with ITV player. I get invalid option --1 from rtmpdump invalid data found. Is this because itv incorporate adverts and it can't locate the stream?

**Comment by NapoleonWils0n** [comment]
HI chrisinodentino

Glad you find the scripts useful

* Could you tell me which operating system you are using:
linux, mac or windows

* Are you trying to record itv live or itv player, 
could you tell me which channel or episode you are trying to record 

Then i can do some debugging
cheers mate

**Comment by chrisinodentino** [comment]
Sorry. I'm running kodi 16.1. Windows 10 64 bit. Itvplayer version 2.3.1. Both streams of live tv and individual on-demand programs show the same issue. Must be drm possibly but strangely bbciplayer and other ondemand plugins work. I would have thought they would use the same protection? Sorry. I'm a novice and installed rip record so I'm not sure how your scripts interact with rtmp dump or how it grabs the streams. If adverts are present does it just find no streams and times out?

**Comment by NapoleonWils0n** [comment]
Hi Mate

Just checked ITV player on Linux, Kodi 16.1, Itvplayer version 2.3.1

The ITV live streams are m3u8 playlists
The ITV Player streams are rtmpe streams

I can record both live and player streams

* Did you install rtmpdump using these instructions
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#rtmpdump

Can you check which version of rtmpdump you are using,
open the windows command prompt and type

```
rtmpdump
```

* the should show you which version you are running, im running rtmpdump 2.4

### updating the scripts with git pull

Can you do a git pull to make sure you are running the latest version of the scripts,
open the windows command prompt and type the following commands

* change into the kodi-playercorefactory folder

```
cd git\kodi-playercorefactory
```

* run git pull to update the scripts

```
git pull
```

Then open Kodi again and see if you can record after doing a git pull

The scripts shouldnt time out for adverts, it will just record them

**Comment by NapoleonWils0n** [comment]
HI Mate

Kodi cant play videos with drm
So that wont be an issue

**Comment by chrisinodentino** [comment]
Thanks. Updated to rtmpdump 2.4. Working like a charm. Rip-record installer needs updating as its still on 2.3. I know this isnt you but just in case anyone else has this problem. Awesome work mate. Shame 4od/fiveod plugins dont work. Having the facility to record from all catchup services would have been great.

**Comment by NapoleonWils0n** [comment]
Hi Mate

have come across that rtmpdump issue before 
and updating to rtmpdump 2.4 solved the issue, glad it fixed it for you

yes 4od and fiveod havent worked for a few years now

id have a look at ukturks addon if you dont have it already
has loads of old and new british tv series

https://seo-michael.co.uk/tutorial-how-to-install-uk-turks-playlists-kodi-xbmc/

**Comment by chrisinodentino** [comment]
Great stuff. Thanks for your help. I'll check uk turk out.

**Comment by NapoleonWils0n** [comment]
HI Mate 

Did you use the new windows installer to set everything up

https://www.youtube.com/watch?v=9hFABPeFUiQ

If so i pass on that the installer isnt installing rtmpdump 2.4

**Comment by chrisinodentino** [comment]
Yes I did and it works albeit the rtmpdump issue. Its taken your scripts and instructions and made it easy for us idiots who are not tech savvy.

**Comment by NapoleonWils0n** [comment]
HI Mate

You also want to check out Phoenix and njm soccer

https://seo-michael.co.uk/how-to-install-phoenix-for-xbmc/
https://seo-michael.co.uk/tutorial-how-to-install-njm-soccer-kodi-xbmc/

**Comment by chrisinodentino** [comment]
Great. Thanks for your help. Very much appreciated.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Yes im working with the guy who made the installer, the t3mni8tor
ill let him know about the rtmpdump issue

he's working on a new installer that will automatically update and download the latest version of the all the programs and schedule git to do a git pull every week to make sure you are always running the latest version of the scripts

with the new installer you only have to click run and it does everything for you, and auto updates as well. 

youll be able to update to the new installer when its out just by downloading and running it

ill close this issue as solved

**Comment by chrisinodentino** [comment]
That sounds cool. Auto updates to programs and scripts would be the icing on the cake.

**Comment by sudhadotsudha** [comment]
Hi Mate, 

I am new to this and learnt many from your document/Videos .   I have few problems,  please help .
my system Configuration :  Xbuntu with kodi 17.

after copying your player factory.xml and bash-scripts ,  i am getting the menu play using ,,,   when I click  record ,  it records only max 5 seconds ( recording ends immediately ) 

what could be the issue ,  how to solve. 

My intention is ,   just want to record some sports tv ( like SKY sports ) , once recording started , i can play the recording video  without lagging or buffering with one minitue delay . 

please help.

**Comment by NapoleonWils0n** [comment]
hi mate

can you check the following 

## bash path

make sure you added the scripts to your bash path

open the terminal and run the following command to show your bash path

```
echo $PATH
```

can you paste the output here

## run script on the command line

open the terminal and run the script on the command line to check it works

```
rip-record
```

that should display the script usage in the terminal

## ffmpeg version

check your ffmepg version by running the following command in the terminal

```
ffmpeg
```

that will display the version of ffmepg you are running

im running ffmpeg 3.2.4-1

the scripts require ffmepg 3.0 and above

you maybe running an older version of ffmpeg in which case you will need unistall the current version and install a newer version of ffmpeg

**Comment by sudhadotsudha** [comment]
Hi  Mate, 

Amazing , it is working fine after upgrade ffmpeg .  Unfortunately i got into another problem. 

*   I am able to play the video but , after some time ,   ,   voice and video getting mismatch .   Now  the video become useless.  i tried both .mkv & .mp4 format. 

looks like while recording if any streaming  issue ( ie slow or server response )   this kind of mismatch .


Please help .     

with regards,

Sudha

**Comment by NapoleonWils0n** [comment]
hi mate

do you get audio video sync problems with all recordings or just one particular stream

have you tried playing the recorded video with several different players

**Comment by sudhadotsudha** [comment]
Hi  Mate, 
Thanks for your reply ,   yes i tried all players  (VLC, MPV , GOM and few more )  ,  same for any stream ( TV  ) 

with regards,

Sudha

**Comment by NapoleonWils0n** [comment]
hi mate

i just did a google for xubuntu audio and video sync

there are quite a few hits for people having audio and video sync issue with xubuntu going back several years

i think this must be an issue with your xubuntu install
maybe you dont have all the codecs installed or something

the scripts just copy the audio and video stream into a new video file
sometimes you can get issues recording a particular stream because of the ways its encoded

but there isnt anything in the scripts that would cause the video and audio to go out if sync

scripts have been tested on windows, mac, ubuntu, ubuntu mate, debian stable, debian unstable, linux mint and freebsd
havent had reports from any other users about your audio video sync issue 

so the issue must be specific to your xubuntu set up

can only suggest googling for "xubuntu audio video sync"
or may be testing on another linux distro

like debian with backports for the latest ffmpeg and kodi
or ubuntu mate perhaps

**Comment by sudhadotsudha** [comment]
Hi mate,

Lovely.  Thanks lot for your detailed mail.

I will try today with different distro.


Meanwhile I would like to share few findings.

I tried to run
 mplayer -fps 25 <filename.mkv >

99% working .  Is there any way to set fps while recording itself.

With regards

Sudhakar


On 19 Mar 2017 12:23 am, "NapoleonWils0n" <notifications@github.com> wrote:

hi mate

i just did a google for xubuntu audio and video sync

there are quite a few hits for people having audio and video sync issue
with xubuntu going back several years

i think this must be an issue with your xubuntu install
maybe you dont have all the codecs installed or something

the scripts just copy the audio and video stream into a new video file
sometimes you can get issues recording a particular stream because of the
ways its encoded

but there isnt anything in the scripts that would cause the video and audio
to go out if sync

scripts have been tested on windows, mac, ubuntu, ubuntu mate, debian
stable, debian unstable, linux mint and freebsd
havent had reports from any other users about your audio video sync issue

so the issue must be specific to your xubuntu set up

can only suggest googling for "xubuntu audio video sync"
or may be testing on another linux distro

like debian with backports for the latest ffmpeg and kodi
or ubuntu mate perhaps

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/NapoleonWils0n/kodi-playercorefactory/issues/58#issuecomment-287556869>,
or mute the thread

**Comment by NapoleonWils0n** [comment]
hi mate

the scripts just copy the audio and video streams into a new container
they should record at the correct framerate but kodi iptv streams can be a bit flaky

what you can do is save the url from kodi
which saves the url into a text file on the desktop

then use the regex-checker script with the text file with the url you saved from kodi

like so, replace video-url.txt with the name of the text file with the saved url from kodi

```
regex-checker video-url.txt
```

that will give you the ffmpeg command to record the stream

if you read the ffmpeg manual about setting the framerate you can then take the ffmpeg code from regex-checker and then add the code to set the framerate

thats probably the quickiest and easiest way 
save the url from kodi run the regex-checker script, get the ffmpeg code then add the code to set the frame rate code

have a read of the ffmpeg manual or have  a google for ffmpeg setting frame rate and you should get the correct code

**Comment by NapoleonWils0n** [comment]
Hi Mate

i think you want something like this:

* To force the frame rate of the output file to 24 fps:

```
ffmpeg -i input.avi -r 24 output.avi
```

ffmpeg manual:
https://ffmpeg.org/ffmpeg.html

**Comment by sudhadotsudha** [comment]
Hi mate ,

Good morning.  Thanks for your mail.

I would like to share my intention.

I want to watch sky sports cricket without lagging or buffering  and most
of the time lag or buffer due to high quality stream.

I am trying to record the video in background  and watch with 1 min  delay
using other player like mplayer/gom player, so buffer or lag .


Am I doing right way?

Please suggest.

With regards,

Sudhakar

**Comment by NapoleonWils0n** [comment]
hi mate

thats exactly what i do sometimes
record the video and watch it is as records with a slight delay

some streams buffer more than others
so really a matter of trying to find the stream that is good quality but that doesnt bufer too much

**Comment by sudhadotsudha** [comment]
Hi mate,


Lovely... How do you manage .. What's your suggestion.

With regards

Sudhakar

**Comment by NapoleonWils0n** [comment]
hi mate

you can find good review about kodi sports addons on this site

https://seo-michael.co.uk

i usually record the stream and leave it for a minute to build up a head of steam
then play the video thats recording on the desktop

hope that helps

**Comment by sudhadotsudha** [comment]
Hi Mate,

This is Sudha Again,   Support required from you again.

using the below , i am able to create .ts files  but  i want to  play in
parallel  in other  window with   ffplay test.m3u8   , always    from
begining of video ( segment or file ) .

how to achieve this.  ( ie i want to watch live with 1 or 2 min delay , but
from the begining  of my download )

window 1 to download:
-------------------------------
ffmpeg -i "http://50.7.1.178/iptvfoxtel/skysports2A/playlist.m3u8"  -f hls
-g 1 -hls_time 10 -hls_list_size 0 -hls_allow_cache 0 -live_start_index 0
-c copy test.m3u8


window 2 to play :
---------------------------

ffplay test.m3u8


Please help.

with regards,

Sudhakar S

**Comment by NapoleonWils0n** [comment]
hi sudha

does that ffmpeg command save the video stream as lots of video.ts files as well as an m3u8 

are you sure the m3u8 file has links to the local video.ts files you recorded and not the video.ts files on the server as it where

have you tried saving the stream as an mkv video file to the desktop and letting it record for a couple of minutes
and then just play the video file on the desktop with ffplay, mpv or vlc

easiest way would be to record to an mkv file leave it for a couple of minutes and then play it
see if that helps

**Comment by sudhadotsudha** [comment]
Hi mate,

Thanks again.

Very valid to use .mkv  but some cases not effective.

Case 1 :if any break or disturbance in download live stream.  Parallel
ffplay get struck and freeze .  Even after few seconds download re-started
and .mkv file being updated.


I.e.,  ffplay av values become 0 bytes
Not able to resume the play.

Do you  have any suggestions to overcome  or is there any way to push
backward 10seconds when ffplay reached av =0bytes.

With regards
Sudhakar.

**Comment by NapoleonWils0n** [comment]
hi mate

i cant think of anything iff the top if my head

i guess one possibility would be to write a script that moniotors the bytes in ffmpeg 
and pushes back 10 seconds when it reaches 0 bytes

you could have a look at mpv player to see if that any better

if i come across anything ill let you know

**Comment by sudhadotsudha** [comment]
Hi Mate,

Cheers , this is Sudha again.  rip-record working very nice with single
.mkv file.

could you please help me ,

is there anyway to  use rip-record method for sportsdevil addon  or
generate the sportsdevil weblink channel out valut to rip-record input for
our recording .

Hope you understand my request.


Thanks again.


with regards,

Sudhakar. S

**Comment by NapoleonWils0n** [comment]
Hi Sudha

You can save the urls from sports devil links by pressing y on the keyboard while the video is playing and selecting save url

that will save the url into a text file with the time and date to the Desktop

you can then open the terminal or windows command prompt if you are windows and use rip-record on the command line to record

open the terminal or windows command prompt and change to the desktop by running this command

```
cd Desktop
```

you can then use rip-record on the command line to record by running the following command
replace videourl.txt with the name of the text file you saved from kodi

```
rip-record videourl.txt
```

if you are on windows you need to run this command

```
bash rip-record videourl.txt
```

you can also set a duration in hours minutes seconds as well like this

record for 1 hour

```
rip-record videourl.txt -t 01:00:00
```

record 30 minutes 

```
rip-record videourl.txt -t 00:30:00
```

if your are on windows you need to add bash before the rip-record command

```
bash rip-record videourl.txt -r 01:00:00
```

you can press control c in the terminal to stop the recording as well

let me know if thats what you where trying to do or not

**Comment by sudhadotsudha** [comment]
Hi Mate,

Very perfect ,  it is working fine with  Y option.

i am getting another problem.   while playing the video.

FYI,  FFMPEG recording the live stream and playing the video after 60
seconds.

play will be closed automatically  when AV: 00:01:52 (99%) A-V:  0.000

reaches 100%


error msg:

playing: /home/sudhakar/Desktop/video-2017-04-19-01-04-18.mkv
[mkv] EBML element with unknown length - unsupported
[ffmpeg/demuxer] matroska,webm: Duplicate element
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 (*) (aac)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:01:52 (99%) A-V:  0.000


Exiting... (End of file)

**Comment by NapoleonWils0n** [comment]
hi mate

have you tried using another video player like mpv or vlc
or leaving the video for a couple of minutes before playing

maybe it hasnt downloaded enough before you start playing and the playhead is reaching the end of the video
