### ISSUE TITLE
Video-link-checker - help

### ISSUE THREAD

**Issue by gabriellluz** [NapoleonWils0n/kodi-playercorefactory#59]
Hi there.
I'm sorry posting again. I can use video link checker out of the box but I'd like to automate things on my media center and I'd like know if I can do those things:

use:
video-link-checker myiptv.m3u8

Can you make possible for video-link-checker to generate a m3u8 like this:
WORKING LINKS:
#EXTINF:0,TSN 1 (hls)(server 8)
http://grandiptv.pw:8000/live/6grandiptv597/77885500/1397.m3u8
#EXTINF:0,TSN 1 (ts)(server 8)
http://grandiptv.pw:8000/live/6grandiptv597/77885500/1397.m3u8
#EXTINF:0,TSN 2 (hls)(server 8)
http://grandiptv.pw:8000/live/6grandiptv597/77885500/1396.m3u8

I want video-link-checker to let me specify a videofiles like this:
video-link-checker myiptvlist.m3u8

and then it gets me a result like this:
#EXTINF:0,TSN 1 (ts)(server 8)
http://grandiptv.pw:8000/live/6grandiptv597/77885500/1397.m3u8
#EXTINF:0,TSN 2 (hls)(server 8)
http://grandiptv.pw:8000/live/6grandiptv597/77885500/1396.m3u8

I want it to keep the #EXTINF: line with the channel name so I can get a perfect m3u8 check.

**Comment by NapoleonWils0n** [comment]
HI Mate
Dont worry about posting, are you using Linux ?

i think i have an older script that might do what you need

https://raw.githubusercontent.com/NapoleonWils0n/cerberus/master/kodi/old-scripts/bash-scripts-linux/m3u8-link-checker

### Heres how to download it and install it

* download the script with wget

```
wget 'https://raw.githubusercontent.com/NapoleonWils0n/cerberus/master/kodi/old-scripts/bash-scripts-linux/m3u8-link-checker'
```

* make it executable

```
chmod +x m3u8-link-checker
```

* create a bin directory in your home if you dont already have one

```
mkdir -p ~/bin
```

* move the m3u8-link-checker into the bin folder

```
mv m3u8-link-checker ~/bin
```

* edit your ~/.bashrc

```
nano ~/.bashrc
```

Check to see if you have this code in your ~/.bashrc 
If not add it and save your ~/.bashrc

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

* source your ~/.bashrc to pick up the new script

```
source ~/.bashrc
```

### using the script

Save your m3u8 file to the Desktop
Change directory to the Desktop 

```
cd ~/Desktop
```

* then run the script

```
m3u8-link-checker
```

* it will prompt you for a m3u8 file or a folder with an m3u8 file in it and then create a file called iptv.m3u8

That should contain the working links and #EXTINF channel info

See if that works

I was going to rewite the video-link-checker script so it uses the same code as the rip- scripts, to check all the urls from kodi
But been working on the Windows installer see latest video for more info on that

**Comment by gabriellluz** [comment]
No, I use Windows but with Cygwin (thanks to you :))

Is there a way to use that script without prompting me to specify a m3u file?
I'm asking you because I'm running it from a server and I want to schedule that bash file like I do with my bat files. But if I have to type the filename everytime I run it, it won't be possible to run it automatically.

I thought I had cygwin but no. I'm installing rip n convert (provided by terminator) on my server now.

**Comment by NapoleonWils0n** [comment]
Hi Mate

Just created new script called m3u8-link-checker and uploaded to github
Do a git pull to update

Doesnt prompt you for a file

All you need to do is run the script with a file

eg:

```
m3u8-link-checker myiptv.m3u8
```

* it then creates a file called filename-checked.m3u8

so it would create a file called myiptv-checked.m3u8

**Comment by gabriellluz** [comment]
Wow!!!!! That's what I wanted. Now my lists can be fully automated. Thank you, Sir. :)  :)  :)

**Comment by NapoleonWils0n** [comment]
Hi gabriellluz 

Updated the m3u8-link-checker script to make sure you that you pass an m3u8 file to the script as the first argument

also prints script usage if you run the script without any arguments

still works the same way checking the links, 
just made the script more robust to check for correct user input 

do a git pull to update
