### ISSUE TITLE
m3u8-link-checker stuck on some PNG files

### ISSUE THREAD

**Issue by gabriellluz** [NapoleonWils0n/kodi-playercorefactory#60]
Hi there, I`m using m3u-link-checker and it really works but sometimes it gets stuck on some PNG files inside m3u8 files. Here`s the m3u8 list I`m testing.
https://bit.ly/pjt-lista (a m3u file, just rename it to m3u8)
I`ve tested other lists and the same happens but it always creates a file called filename-checked with working links.

![captura de tela 2017-01-04 22 53 41](https://cloud.githubusercontent.com/assets/6292535/21664928/bfa614fe-d2d0-11e6-8240-df4841024f4e.png)

**Comment by gabriellluz** [comment]
The screenshot shows a stuck window.

**Comment by NapoleonWils0n** [comment]
hi mate

ill redo the regular expression for links so it doesnt match image file extensions

**Comment by NapoleonWils0n** [comment]
Hi Mate

fixed that issue
changed regular expression to match files ending with m3u8 file extension
thanks for the heads up on the issue with it matching image files

if you have another other issues let me know

**Comment by NapoleonWils0n** [comment]
do a git pull to update and it should resolve the issue

**Comment by gabriellluz** [comment]
Thank you but not all streams end with "m3u8". Some streams end up with .ts and others simply don't have an extension.

**Comment by gabriellluz** [comment]
I guess you could make a rule to ignore only image files (png, jpg, gif, svg etc)

**Comment by NapoleonWils0n** [comment]
hi mate

piped regex into grep again with -v option to exclude image extension

do a git pull and see if that works

**Comment by gabriellluz** [comment]
Hi, the script is really faster now. But when it finishes my CMD window won`t close. Any ideas on how to close it automatically?

**Comment by gabriellluz** [comment]
Ops, I've just added "exit" at the end of the script and it worked. Last time, before the image exclude update, I've add "exit" and it didn't work but now it works.
Man, I suggest you include "exit" at the end too. Otherwise, it won't close automatically and people will think it's stuck.

**Comment by NapoleonWils0n** [comment]
hi mate

the scripts wont automatically close the terminal window
you need to close the window manually

the script do exit cleanly,
the command doesnt hang and need to be killed with control c

if you want to edit the scripts you need to fork the git repository

otherwise if you edit the scripts and try and do a git pull it will either overwrite your changes,
or fail to download the latest version of the scripts because you have made local changes
