### ISSUE TITLE
[ENHANCEMENT] VOD to STRM support

### ISSUE THREAD

**Issue by gabriellluz** [NapoleonWils0n/kodi-playercorefactory#61]
Hi, I have a suggestion.

As you can see nowadays, there's a lot of VOD m3u8 lists packed with movies from many sources around the web.

My suggestion is to create support for converting m3u8 to strm files in order to use it on Kodi. This will create new possibilities:
- you'll be able to import the movies and use it on Kodi on the movie library;
- you'll be able to use STRM for TV channels on TV Guides such as Ivue Guide and other.

That's just a suggestion.

**Comment by NapoleonWils0n** [comment]
Hi Mate

you can just put a m3u8 link in a strm file and it will work

i made videos about creating strm files and custom .ini files for ivue and other tv guides

**Comment by NapoleonWils0n** [comment]
there are kodi plugins like psedo live tv that create strm files as well
