### ISSUE TITLE
Possible to rip-record not from the beginning?

### ISSUE THREAD

**Issue by dxxvi** [NapoleonWils0n/kodi-playercorefactory#63]
The rip-record on my machine is frozen in the middle of the show on my computer without any clear reason.

**Comment by NapoleonWils0n** [comment]
hi mate

badly encoded videos can causes crashes
probably a glitch in the middle of the video

**Comment by NapoleonWils0n** [comment]
hi mate

you can use the regex-checker script with the text file with url from kodi and it will show you the ffmepg command

regex-checker videourl.txt

you can use the -ss 00:00:00 option to set the start time
and =t option to specify a time

have a google for ffmpeg create clip

**Comment by dxxvi** [comment]
Thank you very much. And this plugin is amazing.
