### ISSUE TITLE
Amend pastebin ripper and search operators

### ISSUE THREAD

**Issue by privatesam** [NapoleonWils0n/kodi-playercorefactory#64]
Hi NapoleonWils0n.  I've continued trying to bastardise your useful scripts for my own ends!  I probably should just try and write my own from scratch but your regex with sed and awk is too good for me to match.

At the moment I'm trying to amend the m3u-pastebin-ripper for slightly different terms and with another advanced search operator.  I want to the term 'acestream' and perhaps some channel names into the request which is represented in your script like this:

`https://www.google.com/search?q=intext%3A%E2%80%9D%23EXTM3U%E2%80%9D\
+intext%3A%E2%80%9D%23EXTINF%E2%80%9D\
+site%3Apastebin.com&oq=intext%3A%E2%80%9D%23EXTM3U%E2%80%9D\
+intext%3A%E2%80%9D%23EXTINF%E2%80%9D\
+site%3Apastebin.com&num=$REPLY`

Also I'd like to add the advance search operator for results from the last day only which is:

`&tbs=qdr:d `

Is this an easy amendment to the code to add these things in?

UPDATE:

OK so I only just realised that was a urlencoded URL, decoded the url looks like this:

`"https://www.google.com/search?q=intext:”#EXTM3U”\
 intext:”#EXTINF”\
 site:pastebin.com&oq=intext:”#EXTM3U”\
 intext:”#EXTINF”\
 site:pastebin.com&num=$REPLY" \`

Which is much easier to understand and modify for my own purposes.  MY only question is this, why is it doubled up?

This string of the search query is basically back to back:

`q=intext:”#EXTM3U”\
 intext:”#EXTINF”\
 site:pastebin.com
q=intext:”#EXTM3U”\
 intext:”#EXTINF”\
 site:pastebin.com`

**Comment by NapoleonWils0n** [comment]
hi mate

feel free to chop and change the scripts for you own needs

the script uses the lynx command line browser to dump the links
from memory i think the string has to be urlencoded for lynx

the book you want to read about how to create your own search terms is called
google hacking for penetration testers by johnny long

then you can alter the lynx command and put in different urlencoded advanced google searches

there is a reason why the search term is doubled up
from memory one search is for google the other uses the site operator to search just on pastebin

have a read of google hacking for penetration testers and you should get your head around it

you also want to get hold of 
master regular expressions by o`reilly

also read the bash guide here

http://mywiki.wooledge.org/BashGuide
