### ISSUE TITLE
Getting errors with Krypton on Mac. Log pointing to an error ticket on Kodi site?

### ISSUE THREAD

**Issue by peterjohnjoseph** [NapoleonWils0n/kodi-playercorefactory#65]
Thanks for this great set-up. I'm having trouble getting any external player to work on Kodi Krypton (1st full release from 2/1/17) on Mac OSX Sierra 10.12.2.  I've installed everything correctly (from what I can tell), but videos are not playing with any device and I am getting the following errors in the log below. No matter which player I try to use (VLC, MPV, etc.), I get just about the same errors, and this line right before it stops-

ExecuteAppLinux: Failure: 16896

I believe that is pointing to this ticket on the Kodi site with the title "ffmpeg not recieving/using headers and cookies under certain circumstances". That is available at this link-  http://trac.kodi.tv/ticket/16896

I've attached my log starting at where the error occurs after I click on "Play Using VLC".  Any help would be greatly appreciated, as I'd love to get this to work.

02:17:45.679 T:123145394503680  NOTICE: Initialize pseudo device - requesting stream 0
02:17:47.982 T:140736334107584  NOTICE: ExternalPlayer Filename: $HOME/git/kodi-playercorefactory/bash-scripts-macosx/rip-vlc
02:17:47.982 T:140736334107584  NOTICE: ExternalPlayer Tweaks: hideconsole (false), hidexbmc (true), islauncher (false), warpcursor ()
02:17:47.982 T:140736334107584  NOTICE: OpenFile: /Volumes/RAID 0 Set 1/Media Library/Movies/Assassin's Creed 2016 HDCAM NAKRO/Assassin's Creed 2016 HDCAM NAKRO.avi
02:17:47.982 T:123145398874112  NOTICE: Process: Player : $HOME/git/kodi-playercorefactory/bash-scripts-macosx/rip-vlc
02:17:47.982 T:123145398874112  NOTICE: Process: File   : /Volumes/RAID 0 Set 1/Media Library/Movies/Assassin's Creed 2016 HDCAM NAKRO/Assassin's Creed 2016 HDCAM NAKRO.avi
02:17:47.982 T:123145398874112  NOTICE: Process: Content:
02:17:47.982 T:123145398874112  NOTICE: Process: Args   : "{0}"
02:17:47.982 T:123145398874112  NOTICE: Process: Start
02:17:47.982 T:123145398874112  NOTICE: Process: Hiding Kodi window
02:17:48.863 T:123145398874112  NOTICE: ExecuteAppLinux: "$HOME/git/kodi-playercorefactory/bash-scripts-macosx/rip-vlc" "/Volumes/RAID 0 Set 1/Media Library/Movies/Assassin's Creed 2016 HDCAM NAKRO/Assassin's Creed 2016 HDCAM NAKRO.avi"
02:17:48.881 T:123145398874112  NOTICE: ExecuteAppLinux: Failure: 16896
02:17:48.881 T:123145398874112  NOTICE: Process: Stop
02:17:48.881 T:123145398874112  NOTICE: Process: Showing Kodi window
02:17:48.888 T:123145393967104  NOTICE: Found 1 Lists of Devices
02:17:48.888 T:123145393967104  NOTICE: Enumerated DARWINOSX devices:
02:17:48.888 T:123145393967104  NOTICE:     Device 1
02:17:48.888 T:123145393967104  NOTICE:         m_deviceName      : default
02:17:48.888 T:123145393967104  NOTICE:         m_displayName     : Default
02:17:48.888 T:123145393967104  NOTICE:         m_displayNameExtra: Built-in Output
02:17:48.888 T:123145393967104  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
02:17:48.888 T:123145393967104  NOTICE:         m_channels        : FL,FR
02:17:48.888 T:123145393967104  NOTICE:         m_sampleRates     : 96000,88200,48000,44100
02:17:48.888 T:123145393967104  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_S24NE3,AE_FMT_S16LE,AE_FMT_S16NE,AE_FMT_FLOAT
02:17:48.888 T:123145393967104  NOTICE:         m_streamTypes     : No passthrough capabilities
02:17:48.888 T:123145393967104  NOTICE:     Device 2
02:17:48.888 T:123145393967104  NOTICE:         m_deviceName      : Built-in Output:stream0
02:17:48.888 T:123145393967104  NOTICE:         m_displayName     : Built-in Output
02:17:48.888 T:123145393967104  NOTICE:         m_displayNameExtra: Internal Speakers
02:17:48.888 T:123145393967104  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
02:17:48.888 T:123145393967104  NOTICE:         m_channels        : FL,FR
02:17:48.888 T:123145393967104  NOTICE:         m_sampleRates     : 96000,88200,48000,44100
02:17:48.888 T:123145393967104  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_S24NE3,AE_FMT_S16LE,AE_FMT_S16NE,AE_FMT_FLOAT
02:17:48.888 T:123145393967104  NOTICE:         m_streamTypes     : No passthrough capabilities
02:17:48.888 T:123145394503680  NOTICE: Initialize pseudo device - requesting stream 0
02:17:49.563 T:123145405313024   ERROR: EXCEPTION: XBMC is not playing any media file
02:17:49.571 T:123145405313024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any media file
                                            Traceback (most recent call last):
                                              File "/Users/peterjohnjoseph/Library/Application Support/Kodi/addons/plugin.video.metalliq/resources/lib/meta/video_player.py", line 46, in onPlayBackStarted
                                                self.totalTime = self.getTotalTime()
                                            RuntimeError: XBMC is not playing any media file
                                            -->End of Python script error report<--

[kodi-log-playcorefactory.txt](https://github.com/NapoleonWils0n/kodi-playercorefactory/files/748899/kodi-log-playcorefactory.txt)

Thanks again!
P.J.

**Comment by NapoleonWils0n** [comment]
hi  mate

can you check you have your bash path set up to include the scripts

open the terminal and type

```
echo $PATH
```

and post the output here and ill check its set up ok

**Comment by NapoleonWils0n** [comment]
hi mate

can you also try opening the terminal and typing the following

```
rip-record
```

it should display the script usage if the scripts are installed

**Comment by peterjohnjoseph** [comment]
Path seems to be fine- 
┌─[peterjohnjoseph][PJs-iMac][2.3.0][~]
└─▪ echo $PATH
/usr/local/sbin:/Users/peterjohnjoseph/.rvm/gems/ruby-2.3.0/bin:/Users/peterjohnjoseph/.rvm/gems/ruby-2.3.0@global/bin:/Users/peterjohnjoseph/.rvm/rubies/ruby-2.3.0/bin:/Users/peterjohnjoseph/git/kodi-playercorefactory/bash-scripts-macosx:/Users/peterjohnjoseph/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/peterjohnjoseph/.rvm/bin

And here is the second command-

┌─[peterjohnjoseph][PJs-iMac][2.3.0][~]
└─▪ rip-record
Usage: rip-record [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])


Anything missing there?


Thanks again.

**Comment by NapoleonWils0n** [comment]
hi mate

scripts look like they are installed properly

to work out where the issue is try saving a url from kodi by pressing y on the keyboard while a video is playing and select save url

then open the terminal and change to the desktop by running the following command

```
cd Desktop
```

then try using the scripts on the command to see if playing and recording works

try using rip-mpv to play the url from kodi, by typing the following command, 
replacing videourl.txt with the name of the text fiel withe the url you saved from kodi

```
rip-mpv videourl.txt
```

that should open mpv and play the video

try recording

```
rip-record videourl.txt 
```

press control c to quit 
that should record the video

if that works the issue is a bug in kodi 17 beta and external players on the mac

if the sctipts work on the command line but not from within kodi then the issue is with kodi
and as a workaround youll have to save the url from kodi and record on the command line until the bug with kodi is fixed

you might want to file a bug report with kodi about kodi 17 and external players not working

**Comment by NapoleonWils0n** [comment]
Hi Mate

Just tested latest Kodi release candidate on fully up to update version on Mac Sierra

Playing and record worked fine from within Kodi and on the command line
Try installing the Kodi release candidate and not the nightly and see if that helps
