### ISSUE TITLE
Acestream

### ISSUE THREAD

**Issue by ElektrikSteve** [NapoleonWils0n/kodi-playercorefactory#69]
Is it possible to create a player script or modify vlc script to call acestreamplayer in linux so you can record high quality streams using a vpn?

**Comment by NapoleonWils0n** [comment]
Hi Mate

if you use a vpn all your traffic go over the vpn by default
so you just need to start the vpn and then acestream

i use private internet access £25 a year no logs, no download limits and you can use on 5 devices ar once
you can torrent over the vpn so acestream should work as well

**Comment by ElektrikSteve** [comment]
No what I was wanting was acestream as an external player in your kodi
script instead of straight vlc. So when you are watching an acestream feed
you can record it. Saving as URL doesn't work on acestream feeds through
proteous

**Comment by NapoleonWils0n** [comment]
hi mate

if you read the kodi wiki about external players it might be possible to create player for just acestream urls

so when you are playing an acestream in kodi you could choose to open it in external acestream player

i dont know if there is a setting in the addon that would let you do that
i thought there was an option in the acestream addon that would let you choose a folder to auto record acestream videos to

not sure if you can use the external acestream player to record the stream

but ffmpeg wont record acestream streams as it doesnt understand urls that start with acestream://

**Comment by ElektrikSteve** [comment]
Hi mate
 Acestream player is a modded version of vlc and it has a record button so
if one of your scripts could divert the stream to it after it's gone
through plexus you could theoretically record it at HD. Or am I missing
something?

**Comment by NapoleonWils0n** [comment]
hi mate

you just need to create a new player and rule in the playercorefactory.xml

like this

http://xmtvplayer.com/use-xmtv-player-as-external-players-with-kodi-on-android
