### ISSUE TITLE
Not an Issue more of a comment

### ISSUE THREAD

**Issue by cwh060** [NapoleonWils0n/kodi-playercorefactory#70]
Hi Napoleon, I had to uninstall the Windows version (1.8, 2.0 & 2.2) of Rip-Record and revert back to the manual install of all the programs. Seems the author of the Windows version has gone mia. I was having all sorts of problems with his version of the programs, he was not answering any issues posted, so I just stopped using it and no longer recommend those versions. I do still recommend the manual install you supplied, if anyone is brave enough to go through the steps! 
I've done it so many times, on a variety of Windows machines, I find it easy enough. I updated most programs to the newer versions (Cygwin, ffmpeg). Still works great! Thanks cwh.

**Comment by NapoleonWils0n** [comment]
hi mate

thanks for the feedback mate

i think the t3rminator may be ill thats why he hasnt responded to github issues
i havent heard from him for a while either

i changed the way the scripts work which caused an issue with write permissions on the windows tmp folder
and the installer hasnt been updated to fix the issue

you can manually fix the issue by giving write permissions to the tmp folder in the rip-record folder i believe

the manual install does take about 30 minutes or so to,
but its really just matter of install some programs and editing your windows system path

glad everything is still working for you mate
