### ISSUE TITLE
rip-record batch

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#72]
Hi I'm having a blonde moment, how do we setup a rip-record batch in windows 10 with two saved url links? Dont know if you made a youtube video about rip-recor batch in windows.

                                                                                                           Thank You
                                                                                                                 Steve

**Comment by NapoleonWils0n** [comment]
hi steve

this is the video about batch recording

i havent tried the script for a while

https://youtube.com/watch?v=t3iMKzCn8wo

let me know if it still works

**Comment by steve55792** [comment]
i tried the video with rip-record-batch and it said command not found. Is the video for linux or windows?

**Comment by NapoleonWils0n** [comment]
hi steve

when you run the scripts on windows you need to prefix the script name with bash

```
bash

**Comment by steve55792** [comment]
oh okay thank you

**Comment by NapoleonWils0n** [comment]
hi steve 

when you run the scripts on windows you need to prefix them with the word bash

so you need to run

```
bash rip-record-batch
```

and not 

```
rip-record-batch
```

**Comment by steve55792** [comment]
i used the bash rip-record-batch with the directory folder on the desktop and nothing happened.
directory folder name is url if that helps any.

**Comment by steve55792** [comment]
C:\Users\Steve>bash rip-record-batch
enter a directory path: Desktop/urls  and after it goes back to:
C:\Users\Steve>

**Comment by NapoleonWils0n** [comment]
hi steve

try changing to the Desktop first then run the script and select the url folder

change to desktop

```
cd Desktop
```

run the script

```
bash rip-record-batch
```

then enter the url folder at the prompt

**Comment by steve55792** [comment]
after doing that, it goes back to C:\Users\Steve\Desktop>

**Comment by steve55792** [comment]
now it is working. I had to get new urls . I think because i changed the name of the url  is the reason why it did not work. I probably do another trial and error and see if that was the issue. Anyways what is your thought about the illegal and legal issues about downloading/recording from kodi. They say its a no no but i think if a person use it for their purpose only than it is okay. Is downloading and recording the same?

**Comment by NapoleonWils0n** [comment]
hi steve

glad you got it working

re legal situation it depends on the laws in your particular country
there was a case in the european courts recently which came to the conclusion that watching a copyright stream wasnt illegal

but recording is probably frowned on, but when you watch a streaming video its saving to a temporary cache anyway 

a load of the films and tv shows on plugins like exodus are actually hosted on google video or youtube so it could be argued that google is the biggest copyright infringer

there are other tools like youtube-dl that can be used to download videos from various sources and youtube-dl is avaviable in most linux distro software repositories 

so the scripts arent dodgy in any way and would fall under the same category as other tools like youtube-dl

i dont think it would be very easy for you isp to work out if you are just streaming the video or actually recording it using the scripts

unlike when you use torrents to download videos your isp can see the torrent traffic, 
the http traffic when you watch the video in kodi and when you record it should look the same

you can always use a vpn 
i use privateinternetaccess only £25 a year no logs or bandwidth limits

**Comment by steve55792** [comment]
I am using IPVanish for my vpn I got it a reasonable price for use. I dont know what is the copyright Laws in the USA are. It's not like Im selling any of it, I use it for myself. And i dont reeally trust torrents cause its probably to easy to get busted. LOL, Now if i get a threatning letter or something than i probably get worried, but now Im not. Lol.

**Comment by NapoleonWils0n** [comment]
hi steve

generally the feds or old bill (police) in the uk go after torrent uploaders
or people selling preconfigured kodi boxes with dodgy addons

i have never heard of anyone being nicked for watching streaming content on kodi as its just regular web traffic or getting any letters from isps re copyright infringement

and recording the stream should look like the same web traffic as streaming the video

whereas torrents download and upload at the same time so you are then technically uploading the content and can be classed as uploader

and if you use a vpn you will be fine

you can check for dns leaks that will reveal your ip address using this site

https://www.dnsleaktest.com

and click the extended test

i would also reccomend torrentfreak for finding out about copyright issue and tech news

https://torrentfreak.com

it covers lots of stuff not jusr torrents

**Comment by steve55792** [comment]
Will do, thank you for the help.
