### ISSUE TITLE
Kodi Record Windows

### ISSUE THREAD

**Issue by peterpan192** [NapoleonWils0n/kodi-playercorefactory#73]
Hey,
I installed the Rip-Record V. 2.2 today. Everything works fine. However, when trying to record like you show in one of your tutorials, I get an error message (you can see it on the picture) 
What can I do about it? 
Thanks for your great work,
peterpan
![image](https://cloud.githubusercontent.com/assets/28274542/25595485/3ac0b54a-2ec5-11e7-8a99-0cbb29649592.png)

**Comment by NapoleonWils0n** [comment]
hi peter

i wrote the scripts but another user called the terminator wrote the windows installer

the issue is the tmp folder inside the Rip-Record folder doesnt have write permissions

i think this is the folder location of the tmp folder

```
C:\Program Files (x86)\Rip-Record\Git\tmp
```

im not a windows user

but i think what you need to do is right click on the tmp folder maybe as administrator and select properties and then click the security tab and then click the advanced tab and add write permissions

if you google "windows add write permission to folder"
you will get some hits showing you what to do

if you look inside the Rip-Record folder you should be able to find the tmp folder and the give it write permissions

let me know if that resolves the issue for you

**Comment by peterpan192** [comment]
Thanks for your fast reply! I was able to change the permission-settings. Unfortunately, I got another issue:
![image](https://cloud.githubusercontent.com/assets/28274542/25617593/54cc8102-2f43-11e7-9f8b-490e4bc12917.png)
Do you know what I can do about this?

**Comment by NapoleonWils0n** [comment]
hi peter

sorry your having a bit of bother getting set up

i dont think version Rip-Record version 2.2 uses cygwin 
but from the screenshot it looks like it mentions cygwin in the file path

i can only think its an issue with the windows system path and it cant find where ffmpeg is installed
you could check your windows system path and see if thats the issue

do you have cygwin installed by any chance
that might be causing a conflict

you could try unistalling version 2.2 and installing version 1.8 

i havent heard from the terminator who wrote the windows installer for a while
i know other users had the tmp folder issue,  but havent come across the ffmpeg not found issue

**Comment by peterpan192** [comment]
I just uninstalled version 2.2 and installed version 1.8. Now I'm having a hard time to get a '.txt' when selected 'save url'. Just to get it right: Do I just have to install either version 1.8, , 2.0 or 2.2 and everything should work from there or do I have to edit any files like the 'playercorefactory.xml'? Is 'C:\Windows\System32\cmd.exe' supposed to be the destination for either mpv- and vlc-player in 'playercorefactory.xml'? Yesterday I replaced the path with 'C:\Program Files (x86)\Rip-Record\bin\mpv.exe' as a destination for the mpv-player in the 'playercorefactory.xml'. After that the player opened.. Do I have to make more changes?

**Comment by NapoleonWils0n** [comment]
hi peter

sorry the installer is being a pain

you shouldnt need to edit the playercorefactory.xml file

there is a windows bug where it sometimes forgets what in your windows system path
and it cant find the programs

try editing your windows system path and copying all the text into notepad ++
and save the file to your desktop

then delete your windows system path and click ok, make sure you save the path to a text file first
edit your windows system path and paste the windows system path back i from the text file on the desktop

then try saving the url again
its a windows bug that goes back to windows 7 

if that dowsnt help try unistalling everything and reinstalling

version 1.8 should install a new playercorefacty.xml file for you
in  the video is how you how to unistall a Rip-Record

did you remove version 2.2 of playercorefactory.xml before installing version 1.8

have a look at the video and make sure you followed the steps to unistall everything
try unistalling everything and remove the playercorefactory.xml 

and then run the installer for version 1.8

**Comment by peterpan192** [comment]
Unfortunately, I couldn't get it done in Windows. However, I installed Ubuntu on another machine and was able to get everything working there. Awesome! Thank you so much! I have one last question: I'm running Ubuntu on a computer now. Is it also possible to do the recording on a Raspberry PI 3?

**Comment by NapoleonWils0n** [comment]
hi peter

glad you managed to get it working on linux
yes you can record on a raspberry pi, no problem

you can also send the ffmpeg comands over ssh from ubuntu to the pi and record with the pi to an external drive or mounted share
from within kodi on ubuntu to the pi or use the command line

heres the video explaining the set up

video 100 
sending ffmpeg commands over ssh

https://www.youtube.com/watch?v=IRFz0H0POBK

if you look in the docs folder in the scripts github repo you will see a folder called ssh
in the ssh folder is all the documentation you need to set up ssh on ubuntu as the client and the pi as a ssh server

if you are sending the ffmpeg commands over ssh to the pi you dont need to install the scripts on the pi
just ffmpeg rtmpdump and fdk-aac-dev

on debian fdk-aac-dev is called libfdk-aac-dev

so you can have the pi at home and send the ffmpeg comands to to record over ssh from anywhere in the world
you just need to set up port forwarding on your router

you can also set durations for the recordings and schedule recordings as well

so you could be at work and send ffmpeg commands over ssh to your pi at home to record
from within kodi or one the command line

hope that helps

**Comment by peterpan192** [comment]
Sounds great. I'm going to look into it. If I want to setup my Pi3 to directly record from it, which system do I have to install? Right now I'm using Kodi (it came with Recalbox). Do I have to install Ubuntu on the PI and then run KODI? Or is there another linux system like openelec? (I'm new to Linux) Sorry if I'm asking tedious questions)

**Comment by NapoleonWils0n** [comment]
hi peter

if you want to record directly from the pi you need to install ubuntu or raspbian which is based on debian
and then install kodi, ffmpeg rtmpdump and the aac  codec and the scripts like you did with ubuntu

you cant use openelec because it doesnt have a package manager to install software and it has a read only file system

dont worry mate your not asking tedious questions
we were all noobs once and have to start somewhere

let me know if you need any help and ill try and point you in the right direction
and welcome to linux

**Comment by peterpan192** [comment]
Thanks again! Which Ubuntu-Version do you recommend for the Pi-3?

**Comment by NapoleonWils0n** [comment]
hi peter

i havent used a pi for a while to be honest

i have spoken to some raspberry pi users and there is an operating system called OSMC which some people use
and the they said the scripts worked on OSMC

or you could try raspbian or ubuntu mate
the scripts will work any version of linux

you could always get a couple of sd cards and install OSMC , raspbian and ubuntu mate on them
and see which you prefer
