### ISSUE TITLE
Youtube recording

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#74]

**Comment by steve55792** [comment]
HI NapoleonWilson,
I tried rip-record-batch couple youtube video and all it did is just go back to the command prompt. Also i tried recording the videos from youtube while the video was playing like if ya recording a single video and i got denied  and it can not create a temporary file, line 72,73,79 . weird.

**Comment by NapoleonWils0n** [comment]
hi steve

for rip-record-batch you need to do the following

create a folder on the Desktop and give the folder a name like urls
then save the text files with the links you want to record and put them in the Desktop urls folder

then open the windows command prompt and change directory to the desktop

```
cd Desktop
```

then run the rip-record-batch script

```
bash rip-record-batch
```

and enter the name of the folder at the prompt
eg: urls

re cannot create temporary files

thats an issue with the windows installer for the scripts not having write permission on the tmp folder

i think the location of the tmp folder is here

```
C:\Program Files (x86)\Rip-Record\Git\tmp
```

you need to right click on the tmp folder above maybe as admin and select properties then the security tab
then click the advanced tab and add write permissions

im not a windows users and didnt write the windows installer
but i think its an issue with the write permission on the tmp folder i mentioned

**Comment by steve55792** [comment]
Thanks Napoleon, its working now.

**Comment by NapoleonWils0n** [comment]
hi steve

glad you got it working again

i close the issue

**Comment by steve55792** [comment]
is it possible to move the completed file to a networked drive after it gets done recording because i wanna move my videos fom  c://videos to my wdmycloud network drive.
