### ISSUE TITLE
Not n Issue

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#75]
Hi Napoleon, This is no issues with the program, but im curious what setting should i set my ipvanish to record shows/movies, channels? I tried BBC1 for a second and it need to be on UK servers but not on other servers. Isnt there some servers they say not to use because of the new law they have now.
                                                                                                                 Thank You
                                                                                                                      steve

**Comment by NapoleonWils0n** [comment]
hi steve

you will need to be connected to a vpn in the uk to watch bbc

im not sure about the set up for your vpn provider, but you should just be able to connect to a uk server

the law in europe just changed so streaming copyright videos is now illegal as well
which technically means watching something on youtube if it is copyright is illegal

**Comment by steve55792** [comment]
sooooooo dont have my vpn set to europe. what about the iptv service i pay for, is that illegal even if i pay for it? What do you people over there do that wanna watch something on kodi, probably the same what others are doing, vpn service. Lol, what about Youtube and Google, are they gonna shut them down too. Shut one down another one comes to take over, just like they did to Napster.

**Comment by NapoleonWils0n** [comment]
hi steve

you only need to set vpn to europe if you want to avoid geoblocking and want to watch uk tv

most paid iptv services tend to be a bit dodgy

in the uk there are over 300 blocked sites like file lockers streaming sites and torrent sites
so a lot of addons like icefilms and 1channel are blocked as well as where the videos are hosted

so you do need to use a vpn

**Comment by steve55792** [comment]
ok, thank you Napoleon.
