### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#76]
Is there an update lately cause I cant even watch something from mpv? It says enied permissions but i know everything is checked in permission section.

                                                                                                  Thanks
                                                                                                    steve

**Comment by NapoleonWils0n** [comment]
hi mate

i havent made any updates to the scripts

i forget are you on windows or linux
sometimes on linux when you update ffmpeg mpv stops working until the next day when they release a new mpv update

if its windows it could be the permissions on the tmp folder in the rip-record folder

has mpv stopped working completly or can mpv play video files from the desktop for example
if mpv is working but not with the scripts i would guess its the tmp folder issue i mentioned above

**Comment by steve55792** [comment]
mpv play files fine and i started recording and it started be denied and after it started recording fine but i  did not try rip-record-batch yet tho.

                                                                                                             Thanks
                                                                                                                  steve

**Comment by NapoleonWils0n** [comment]
hi mate

so you mean if you start a recording 
and the  try and play the video on the desktop with mpv it wont work until it has finished recording

**Comment by steve55792** [comment]
When i play a video in kodi and i click y on the keypad to play with mpv  it'll start with the denied line 60 and 61 with permission denied, same thing withe the recordinf and eventualling it will start recording.

**Comment by steve55792** [comment]
Ill try to send a picture to show what im talking about later, gotta get ready for work lol.
