### ISSUE TITLE
M3U8 bash script in Python

### ISSUE THREAD

**Issue by Thefunkymunkee** [NapoleonWils0n/kodi-playercorefactory#77]
Hi 

Very sorry to trouble you.

Is there any chance that the M3U8 script can be converted to run in python. I have an Android phone and I cant seem to run the bash script on my phone. I can run all different manner of Python scripts and I was wondering if this was possible.

**Comment by NapoleonWils0n** [comment]
hi mate

funny you should mention that

im actually rewriting the main script in python
im about a third the way thru the rewrite

but it will be a while as im teaching myself python as i go
plan is to rewrite the script in python and eventually turn it into a kodi addon

**Comment by RenegadesTV** [comment]
Did you manage to get anywhere with this?
