### ISSUE TITLE
.ts file

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#78]
Hi, would you know how to make my new iptv service link into a m3u link?   http://limitless-iptv.is-found.org:25461/get.php?username=Steve Turman&password=8UCNj8lOzL&type=m3u&output=ts

I was thinking if delete the end of link : &output=ts. Is there a way to use kodi-playercorefactory to record think iptv link. I tried but no success.

**Comment by NapoleonWils0n** [comment]
Hi Steve 

You can put that link in a .m3u8 text file, 
but i dont think the script will catch that url to be honest

What you could try is playing that url in a video player like mpv, ffplay or vlc and see if it plays

Then use wireshark while its playing and see if you can find the link,
i made a couple of videos about using wireshark

There is also another command line tool called quvi that can record videos stream
That might be worth having a look at but i cant swear that it will work, but it might be useful to have in the toolbox

http://quvi.sourceforge.net/

Also im just rewriting the rip-record script in python,
but im having to teach myself python first so it doesnt record or do anything at the moment

https://github.com/NapoleonWils0n/rip-record

im just working on how to chop up the kodi url at the moment
and then rearrange into an ffmpeg command to record the stream

some of the new features im looking to add are detecting if the stream is using a local proxy
( like with kodi sterams where its says starting local proxy using f4m ) and then using the f4m python script from kodi to start a local proxy and then record thru it

it will also decode url encoded links, for example when spaces are converted to %20 in the url

once i have got the python script working as a command line tool the next step would be to convert the python code into a kodi addon

but i dont know python so im having to read a lot of books and manual, and watch lots of python 3 video tutorials first, so will take me a while to 

i have the done first part of the script which validates user input to make sure you add a proper url or a text file with a url and the correct options for the recording duration

im now working on searching inside the url for thing like user-agent, referer, cookies etc and extracting them, then after that i can start work on rearranging the bits into an ffmpeg command

but it will take me a while to get my head around python

**Comment by steve55792** [comment]
do you know how to use the quvi?

**Comment by NapoleonWils0n** [comment]
hi steve

i havent used quvi to be honest

if you google quvi there is an arch linux wiki page about it, 3rd google hit
that has little bit of info on it

you could also look at livestreamer

not sure if they will work but might be worth a try
