### ISSUE TITLE
Remote Access to Raspberry Pi that is connected to VPN

### ISSUE THREAD

**Issue by peterpan192** [NapoleonWils0n/kodi-playercorefactory#79]
Excuse me for asking a little off-topic. However, you helped me a lot with my last question so I thought I could ask you about this as well. I recently set up my new router with DynDns and portforwarded one port to my Raspberry Pi where I have your scripts installed. (Everything runs well with OSMC) My intention was to ssh to my Pi from anywhere which works well via terminal with the command 'ssh -p'x'(open port) osmc@External Ip of my router' Now to my question: What do I have to do to be able to connect to my PI from anywhere if it's connected to a VPN? I have VPNs running on it with OPENVPN. As soon as I connect to a VPN-Server, I cannot remote access it anymore which makes a little sense to me. The Pi has another external IP, alright. But it is still connected to a router so there should be a way to access it, right? Thanks in advance, Peter Pan

**Comment by NapoleonWils0n** [comment]
Hi Peter

not off topic at all mate
so you have the pi running as an openvpn client that connects to a vpn server, 
and when you do that you cant ssh into the pi from outside is that correct

i think it may be an issue with the vpn changing the gateway and iptables ( firewall )

i dont know if this link helps
https://serverfault.com/questions/659955/allowing-ssh-on-a-server-with-an-active-openvpn-client

I have a guide on how to send recording commends from within kodi or on the command line via ssh to a raspberry pi to record 

* sending ffmpeg commands over ssh
https://www.youtube.com/watch?v=IRFz0H0POBk

* ssh client and server set up
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/docs/ssh

the other thing you can look at is split vpn routing, 
i have some notes and scripts for setting up a split vpn route

* openvpn notes
https://github.com/NapoleonWils0n/cerberus/tree/master/openvpn

* openvpn split routing scripts
https://github.com/NapoleonWils0n/bin/blob/master/vpn-split-route.sh
https://github.com/NapoleonWils0n/bin/blob/master/openvpn-up.sh
https://github.com/NapoleonWils0n/bin/blob/master/openvpn-down.sh

my guess is that its an issue with openvpn changing the default gateway and iptables
hope that helps point you in the right direction

**Comment by peterpan192** [comment]
Thank you very much! It makes a lot of sense to me what you said and what John Doe writes at serverfault.com (your first link) However, I am not sure where I have to copy what he wrote and what I would have to insert for '1234' , '4321' and '3412'. Can I just add it to my openvpn.conf-File?

**Comment by NapoleonWils0n** [comment]
hi mate

those are commands for iptables firewall which are run in the terminal
you wouldnt add them to your openvpn config file

so you can connect over ssh to the pi, 
but if you are running the openvpn on the pi you cant connect to it via ssh

what firewall are you using the pi
have you opened the port for the ssh server

how are you starting openvpn on the pi on the command line or using a gui program

when the vpn is running you could use nmap to scan the pi and see if the ssh server port is open

the vpn creates a tun network device with a 10.00.00.00 subnet
you can see the network interfaces and ip addresess by running

```
ip a
```

or 

```
ifconfig
```

normally you local network interface would be i the 192.168.0.0 range
maybe the ssh servis configure to accept connections only on the 192 subnet and not on the vpn subnet

may also be a firewall issue which would probably be iptables

you could try asking about your issue on the openvpn irc channel or on stackoverflow

**Comment by peterpan192** [comment]
> so you can connect over ssh to the pi,
but if you are running the openvpn on the pi you cant connect to it via ssh

Exactly.

> what firewall are you using the pi
have you opened the port for the ssh server

I have not installed a firewall on my Raspberry Pi. Should I?
The port is open.

> how are you starting openvpn on the pi on the command line or using a gui program

I can either start it via command line or using the gui on the Pi with both the same outcome: Connection gets lost.

> you could try asking about your issue on the openvpn irc channel or on stackoverflow

I reopened two threads in other forums where people had similar issues. We can leave this issue here open so I can post my solution If I find one. 
Thanks again for your help!

**Comment by NapoleonWils0n** [comment]
hi peter

you should use a firewall on the pi
iptables is what most people use

you can use iptables on the command line and there are probably some gui tools for it as well

**Comment by NapoleonWils0n** [comment]
hi mate

ill close this issue but if figure out the problem open another issue
and ill add the solution to the ssh docs on github
