### ISSUE TITLE
netflix and hulu?

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#81]
Hi, Napoleonwilson:

I know your busy, i was wondering in Ubuntu with kodi, if there's an addon for netflix and hulu. For some reason i can't find it for windows 10 in kodi.

                                                                                     Steve

**Comment by NapoleonWils0n** [comment]
hi mate

no netflix or hulu plugins for kodi

used to be hulu plugin but it stopped working years ago

**Comment by steve55792** [comment]
What a bummer, I was going to stream legally LoL but no Netflix or Hulu for Kodi.LOL.

**Comment by steve55792** [comment]
With all the Kodi having legal issues with 3rd party addons
