### ISSUE TITLE
playercorefactory for android

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#82]
Hi, NapoleonWilson:

  How is your new project coming, with python and extracting urls and whatever else you mentioned to me before when we talked. Anyways I was wondering if there is a playercorefactory.xml  for android because i decided to use my nivida shield again. I tried looking for a screen capture app for android but I havent had any luck finding a good one for nivda shield tv. Didnt you mentioned before that wireshark can extract more than one link in kodi? If there's no playercorefactory.xml for android, i probably just record on Windows and somehow transfer to Nivida shield tv  folders.

**Comment by NapoleonWils0n** [comment]
hi steve

on the python project i have worked out how to chop up the url into bits like user agent, referer etc
but at the moment i can only access one of the chopped up bits like user agent but not the referer
so having to do some research to fix the issue

no joy on the android front, so no playercorefactory for android im afraid

streaming from windows to android
you can stream videos from kodi or on the command line to your android device

have a look at videos number 40 and 41 
and have a look in the docs folder on github and the multicast streaming folder for more info

wireshark can capture multiple urls from kodi, you just run wireshark and capture traffic from your network interface
then you can open videos in kodi and wireshark will capture the url
you can then export all the captured links at once

have a look at video 69 on how to install wireshark and windump on windows
and have a look at videos 70 and 72 on how to use wireshark with kodi

and look in the docs folder on github and the windump folder for more info

hope that helps

**Comment by NapoleonWils0n** [comment]
hi mate

the rip-stream script can stream local files stored on your computer
as well as streaming remote files on the internet

so you can record files on windows then stream the files you have recorded from windows to android
the rip-stream script actually does multicast streaming which means it can stream to all the devices on your network at once

streaming will work better if both devices are plugged in with ethernet
but can also stream over wifi as well

may save you from having to transfer files from windows to android
