### ISSUE TITLE
Solution for 'Remote Access to Raspberry Pi that is connected to VPN'

### ISSUE THREAD

**Issue by peterpan192** [NapoleonWils0n/kodi-playercorefactory#83]
I figured it out: A month ago, I opened an issue because I couldn't ssh into my Raspberry Pi (OSMC) when it was connected to a VPN-Server. First you need to create the file 'autoexec.py' in .kodi/userdata. Then you write the following lines into that: 

import xbmc
xbmc.executebuiltin('XBMC.RunScript(script.openvpn,"name_of_your_VPN*)')   

*It has to be the same name as in the OpenVPN-Addon in KODI.

By doing this, you made sure that everytime you start KODI, it will connect to the particular VPN-Server.

To be able to remote access your device, you need to create the file 'up.sh' in etc/openvpn and make it executable. The file should look like this:

#!/bin/sh
ip rule add from 192.168.1.19 (the ip your device has in your home-network) table 128
ip route add table 128 to 192.168.1.0/24 dev wlan0 (use eth0 if your device is connected via LAN)
ip route add table 128 default via 192.168.1.1 <-- your Router-IP

Last but not least, you add these two lines to the beginning of your 'name_of_your_VPN'-file. You can find it in .kodi/userdata/addon_data/script.openvpn

script-security 2
up /etc/openvpn/up.sh

Voila, that's it. Now your device auto-connects to your chosen VPN and you can remote access it via your public Router-IP anyways.

**Comment by NapoleonWils0n** [comment]
hi mate

brilliant work mate
glad you managed to figure it out

ill keep a record of your tip and will add it to the github docs when i get a chance
