### ISSUE TITLE
rip-record a particular part of a stream

### ISSUE THREAD

**Issue by peterpan192** [NapoleonWils0n/kodi-playercorefactory#84]
Hey, it's me again,
is there a way to use rip-record to only record a part of stream? Let's say, I wanted to record the last five minutes of a 59 min long stream. 
Thanks in advance!

**Comment by NapoleonWils0n** [comment]
hi mate

you can specify a duration for the record from within kodi or on the command line

you should see options to record for several different durations when you press y while a video is playing in kodi

if you are on the command line you can specify a time as well like this 

to record for 1 hour

windows

```
bash rip-record 'http://example.com/video.m3u8' -t 01:00:00
```

linux

```
rip-record 'http://example.com/video.m3u8' -t 01:00:00
```

time is specified in hours minutes seconds

30 mins

```
-t 00:30:00
```

you can also schedule records with a duration

so you just need to schedule the recording to start at the last 5 mins of the program
and set a duration for 5 minutes

```
rip-record 'http://example.com/video.m3u8' -t 00:05:00
```

hope that helps

**Comment by peterpan192** [comment]
Thanks for your help again. I think, I didn't put it clear enough. Let's say it's not part of a live stream. I want to record/download a part of a static stream where an mp4 or mkv lies on a server.

**Comment by NapoleonWils0n** [comment]
hi mate

i get you

you will need to run the ffmpeg commands manually in the terminal

but thats the best way to learn, 
by reading the manually and finding the command line options you need to get the job done

heres what you need to do to record by specifying a start and end points for the record from a static file

what you want is ffmpegs seek function with the time to option
seek uses this option

```
-ss 00:00:00
```

seek into the video stream in hours minutes seconds
start record at 55 mins for example

time to uses this option

```
-to 00:00:00
```

time to record to a certain time in the video

have a look at this page and scroll down to
Notes cutting small sections

https://trac.ffmpeg.org/wiki/Seeking

also id recommend reading the ffmpeg manual
really helps to know all the different ffmpeg options

https://ffmpeg.org/ffmpeg.html

you can also read the ffmpeg docs in the terminal as well

just type the following in the terminal

```
man ffmpeg
```

if your on windows you may need to do 

```
bash man ffmpeg
```

and press q to quit the ffmpeg man page

hope that helps

**Comment by peterpan192** [comment]
Awesome! It worked! Thanks again!
