### ISSUE TITLE
Kodi 

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#86]
Hi Napoleon,
Everythings been running like a dream fine for ages no hiccups and then suddenly both iplayer and the hub have both stopped working on Kodi v17.3.
Do you know of any reason for this??

Many Thanks 
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs

i noticed the categories  on iplayer stopped working a few days ago
and only the live tv links where working

but everything on iplayer started working again for me yesterday

i noticed the iplayer ios app now requires you to sign into watch
apparently you will have to sign into iplayer with the email address you used to buy a tv license with soon

so im guessing the kodi addon may soon require a email login as well
unless they find a way around it

not sure about itv hub
that may just be an issue where the itv hub layout has changed and the addon hasnt been updated

**Comment by Sparkplugs** [comment]
Thank you for he update Napoleon, I'll wait to see what happens.

On a totally different note, sometime ago you suggested that I should opt for Debian rather than Mint because of the use of its backports and there are a lot more things you can do with Debian, which i really wanted to do. But I've tried installing Debian Jessie and Debian Stretch and for some reason I cannot get Debian to recognise my Nvidia GPU. I've tried everything, forums, youtube, I've tried it with bumblebee, downloaded the drivers direct from Nvidia and from Debian wiki. I've followed the instructions to the letter but everytime I reboot after the installation the light manager crashes and I just get the black screen of death. I'd Install the nvidia-xconfig package, then run it and it should automatically generate a Xorg configuration file at /etc/X11/xorg.conf. But Debian just doesn't see the GPU which I think is causing the black screen after I generate the xorg.conf, it recognises the onboard intel one eveytime.
My GPU is nvidia GTX960M. 

Sorry for troubling you with this I know that it has nothing to do with kodi and playercorefactory but your my only hope. Do you have any suggestions?

Many thanks
sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs 

also make sure you arent still using tvaddons repo fir your addons
if you read torrentfreak youll see the tvaddons domain has been taken over by a law firm in the states

im using the superrepo at the moment

infound debian to be pretty stable
but couldnt swear it will work with nvidia

what login manager are you using light dm
have you tried using gdm

or using startx instead of login manager

what desktop enviornment are you using gnome
maybe something like compiz for effects

have you tried a different desktop enviornment like mate or xfce
or you maye have to try another distro

**Comment by Sparkplugs** [comment]
Hi Napoleon,

Yes I'm also using superrepo.
I've only tried xfce at the mo but will try it using mate and startx to see if that makes a difference.
Failing that i will try another distro have you any you can recommend?

**Comment by NapoleonWils0n** [comment]
hi mate

i probably suggest ubuntu instead of debian

**Comment by Sparkplugs** [comment]
I tried startx but made no difference. When I run 'nvidia - detect' it says 'no gpu detected' so it must be because Debian doesn't see the nvidia gpu. I'll have to try other distros like you suggested. Does ubuntu do backports as well?
Going back to kodi, I just very recently moved, would the change of ip address mess kodi up with the likes of iplayer etc. Is it worth removing it totally and re-installing it? Just seems a bit of a coincidence that everything was working fine before the move.

I saw six men kicking and punching the mother-in-law. My neighbour said 'Are you going to help?' I said 'No, Six should be enough." - The late great Les Dawson.

**Comment by NapoleonWils0n** [comment]
hi mate

ive never really used nvidia

im running debian unstable on an old macbook air
also running freebsd on my other macbook air with kodi and all the scripts

have you followed the steps on the debian wiki

https://wiki.debian.org/NvidiaGraphicsDrivers

have you added contrib and non free to your sources.list
installed linux headers and the nvidia=driver
created the xorg file and restarted

ubuntu is based on the debian unstable branch i think
i dont think ubuntu does backports

you could check in a browser if the superrepo is blocked by your isp
could also try reinstalling the addon

love the les dawson joke

**Comment by Sparkplugs** [comment]
Hi Napoleon,
Followed your instructions/advice and Debian is now working like a dream and with nvidia working. 
I also found an addon for kodi called noobs and nerds repo, which have iplayer etc working, hopefully superrepo will sort theirs out soon. 
A while ago you mentioned a way of running your own dns server so that my isp wouldn't have a record of my dns request. Could you please ping me over the instructions (or point me to the website) on how to set it up.
Without guys like you, I wouldn't have a clue on setting all this up, really appreciate it mate.

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs

glad you got debian and nvidia working
i use the noobs and nerds repo as well

there is a new addon called covenant which is by the people who made exodus

heres the link to the zip

https://raw.githubusercontent.com/Colossal1/repository.colossus/master/repository.colossus/repository.colossus-999.999.6.zip

just going to have my dins
then ill send you over my dns server set up guide

means you can do cool stuff like adblocking with dns

**Comment by NapoleonWils0n** [comment]
hi mate

just writing the instructions out
and copying all the config files from my debian machine

will upload to github after i have finishec writing the how to

**Comment by Sparkplugs** [comment]
Hi Napoleon,

Great, thank you very much. 
Noobs n nerds have Elysium on there as well, which is pretty cool.
Specto has been a bit hit n miss lately so I'll give covenant a go.

**Comment by NapoleonWils0n** [comment]
hi mate

finished writing the guide

will upload to github shortly, 
just need a cup of tea and chocy biccy

also here's ukturk addon new version

https://addoncloud.org/ukturk/install

**Comment by NapoleonWils0n** [comment]
hi mate

uploaded unbound dns server guide and config files to github

this will set up a local dns caching server with dnssec validation to secure your dns queries
and also block ads on the dns level

the unbound dns server is only listen on localhost by default

if you want to have other computers use the dns server 
you need to change unbound to listen on its lan ip address instead of localhost in the unbound config

eg something like 192.168.1.8

you can find you ip address with the ip command
i think this is the correct command

```
ip a
```

and also open port 53 with iptables[]()

* unbound dns server with adblocking set up guide

https://github.com/NapoleonWils0n/cerberus/blob/master/debian/debian-unbound/debian-unbound.md

* config files

https://github.com/NapoleonWils0n/cerberus/tree/master/debian/debian-unbound

* cerberus repo

i keep all my tech notes in this repository, 
if i know the answer it will be in the cerberus repo

you might want to clone the repo so you can grep "search" for tech tips

https://github.com/NapoleonWils0n/cerberus

let me know how you get on

i have been using this set up for several years on arch, debian and freebsd and it works like a charm

**Comment by Sparkplugs** [comment]
Excellent, thank you very much, great stuff.
That'll keep me busy for weeks.

I haven't spoken to my mother-in-law for two years.  We haven't quarreled.  I just don't like to interrupt her.

**Comment by NapoleonWils0n** [comment]
hi mate

should take about 10 minutes or so to set up the dns server

i have lots of tech tips in the cerberus repo
should keep you busy for a while

are you channeling les dawson

**Comment by NapoleonWils0n** [comment]
hi mate

bbc iplayer and covenant are in the superrepo

just though id give you aheads

**Comment by NapoleonWils0n** [comment]
up

**Comment by Sparkplugs** [comment]
That's great stuff, I really appreciate all that you've done, thank you.

You can't beat Les Dawson's mother-in-law jokes, especially when you have a mother-in-law like mine.
It helps me get through the day, when I'm with her lol.

Thanks again
Sparkplugs

**Comment by NapoleonWils0n** [comment]
hi sparkplugs 

no problem mate anytime
always good to share tips and tricks

 by the way i use privateinternetaccess.com for a vpn

£25 a year you can use it with 5 devices at once, no logs
and it has vpn severs all over the world

also works with unbound dns server
so you dns queries go over the vpn 

so if you connect to a vpn server in the usa your dns will come out in the usa
you can check with the dnsleaktest site

ill have to find some les dawson and bob monkhouse clips
