### ISSUE TITLE
cant record

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#87]
Hi Napoleonwilson,

Now I cant do anything with the rip-record of t3rminator's. Is he still working with it, haven't seen him on here much lately. I tried with the kodi-playercorefactory too , it wont use the mpv player or leave a video stats or do anything. I tried all versions of rip-record.

                                                                                                  thank you
                                                                                                     steve

**Comment by NapoleonWils0n** [comment]
hi steve

sorry everythings gone pear shaped and stopped working

im not a windows expert
so only thing i can thing of is what you have probably already tried

unistalling everything and editing your windows system path
must be something left over somewhere

the terminator is about
raise an issue on the github page and explain the problem

ill let him know your having an issue

by the way
i have just rewritten rip-record in python

the python version is called segment
works exactly the same as the bash version but should catch more urls

i just need to package it up so you can install it with python pip from github
and write the documentation and do a video about

hopefully should be ready in the next week or so
