### ISSUE TITLE
Ubuntu Mate

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#88]

**Comment by steve55792** [comment]
Hi NapoleonWilson, 

I decided to reuse Ubuntu Mate for everything while t3rmin8tor figure out the issue with windows 10, I think i got everything setup correctly, I think. When i try to use mpv , nothing happened. and when i try to record it says within seconds  "finished recording", try looking for the video on the desktop and there is nothing. What's the proper way of installing everything on Ubuntu mate again, i went withyour instructions in the read.me section, Of course if i did it correctly it should work, but i must of missed a section.
                                                                                                        Thank you
                                                                                                             steve

**Comment by NapoleonWils0n** [comment]
hi steve

did you add the path to the scripts in your bashrc

run the following command in the terminal to double check

```
echo $PATH
```

it should show the path to the scripts

did you download the scripts with git into the git folder in your home

from memory i think it might be the ubuntu mate ffmpeg version is too old
you can check the ffmpeg version on the command line by running this command

```
ffmpeg -v
```

you need above version 3.0

you can see if there is a ppa for a newer version of ffmpeg

yes just follow the instructions on the front page of the repo

**Comment by steve55792** [comment]
i think i did it correct, here is the outcome:/home/me2/git/kodi-playercorefactory/bash-scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
and i had to update the ffmpeg also. when updating the ffmpeg it said this: Missing argument for option 'v'.
Error splitting the argument list: Invalid argument

**Comment by NapoleonWils0n** [comment]
hi steve

your path looks correct

what happens if you type 

```
rip-record
```

in the terminal does it display the script help

not sure about the error you are getting trying to update ffmepg

to update linux you usually just run

```
sudo apt update
```

then 

```
sudo apt upgrade
```

**Comment by steve55792** [comment]
the rip-record said: Usage: rip-record [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])

and when i add a url text to it: /home/me2/git/kodi-playercorefactory/bash-scripts/rip-record: line 28: file:///home/me2/Desktop/video-url-2017-09-06-22-48-42.txt: No such file or directory
'file:///home/me2/Desktop/video-url-2017-09-06-22-48-42.txt' invalid input
Usage: rip-record [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])

**Comment by steve55792** [comment]
Now everything is working fine now. all i need to find out how to setup ipvanish with ubuntu mate. Do you know how to setup ipvanish in ubuntu mate?

**Comment by steve55792** [comment]
Here is a weird question, do they know on the other side when a person record the movie or tv show? I might wanna have ipvanish runniing anyways.

**Comment by NapoleonWils0n** [comment]
hi mate

ubuntu ipvanish set up

https://www.ipvanish.com/visualguides/OpenVPN/Ubuntu/

i dont know if ipvanish keep logs
i use privateinternetaccess £25 can use on 5 devices at once and no logs

i dont think the internet traffic looks different if you are watching vs recording

**Comment by NapoleonWils0n** [comment]
hi mate

noticed your thread on the windows installer that its working in ubuntu as well

so ill close this issue

**Comment by steve55792** [comment]
Thank you again NapoleonWilson for the time and patience.

**Comment by steve55792** [comment]
Hi NapoleonWilson, is it hard to setup privateinternetaccess  in ubntu mate? I tried with ipvanish but the vpn connections is greyed out when trying to add ipvanish.
