### ISSUE TITLE
playercorefactory.xml

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/kodi-playercorefactory#9]
Hi Napoleon,

Love you're work.
I'm a total novice at this so please bear with me.
I've been following your Kodi recording videos on Youtube and the playercorefactory.xml file is different (in your github) to the one you refer to on Youtube videos 1& 2. 
How can I get that coding or is it obsolete and been superseded?

Many Thanks
Sparkplugs

**Comment by NapoleonWils0n** [comment]
Hi Mate
Everyone was a noob once dont worry

The code in Youtube videos 1 & 2 is when i was just working out stuff and has been superseeded by the new code on the kodi-playercorefactory git repo

You can ignore the code in the first videos, watch the videos links below instead for your operating system

what operating system do you use ?

you need to follow the instructions for your operating system in the videos and read me pages. 

the code works on windows ( including windows 10 ), mac osx ( including El Capitan ) and linux ( tested and working on ubuntu, debian and arch linux )

If you are on windows follow this video:
https://www.youtube.com/watch?v=syiIx8y__PY

and follow the windows read me page:
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows

If you are on a mac follow this video:
https://www.youtube.com/watch?v=nULCurjynVU

and follow the  mac osx readme page:
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/macosx

if you are using linux you can follow the main read me
https://github.com/NapoleonWils0n/kodi-playercorefactory

There is also documentation in the docs section in the git repo
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/docs

If you get stuck leave and a comment here and ill point you in the right direction

**Comment by Sparkplugs** [comment]
Hi Napoleon,

Thank you for your quick response. I will check out the attached.

The OS I'm using is Linux Mint - Cinnamon, which I'm also a novice at but after research it appeared to be the way forward in what I'm trying to achieve. Which is basically - to record my favourite streams because I'm currently in Canada on a two year contract and with the time difference I can then watch them at my leisure.
I'm sure I'll be in touch again soon, thanks again for all your work.

Sparkplugs
