### ISSUE TITLE
M3u8 Script in Python - PLEASE

### ISSUE THREAD

**Issue by RenegadesTV** [NapoleonWils0n/kodi-playercorefactory#91]
Hi

Very sorry to trouble you.

Is there any chance that the M3U8 script can be converted to run in python. I have an Android phone and I cant seem to run the bash script on my phone. I can run all different manner of Python scripts and I was wondering if this was possible.

**Comment by NapoleonWils0n** [comment]
hi mate

dont have the time or an android to test on
you can run the script on a windows mac linux or unix machine
