### ISSUE TITLE
rip-record*/rip-ssh: Handling tokens in URL

### ISSUE THREAD

**Issue by K3rm1t4** [NapoleonWils0n/kodi-playercorefactory#92]
First of all, I'd like to say thanks for this project - great job!

Any chance you could enhance the rip-record*/rip-ssh scripts (maybe others as well) and add support for URLs that include tokens in cookie parameters like the following?

Ex.
`https://vod-i-video-nfl.akamaized.net/vod/4ba9bce7-d1c7-424d-aa48-40286cd38eb6/3_57160_nyg_gb_2016_h_whole_1_6000.20170526074931.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1498126034~exp=1498126049~acl=/*~hmac=f4ebff6184f3a6f0b57c9b5de1ba88a6c7ea9d21318a1acdc172df798a66f77f&hdcore=2.11.3`

`https://nlds120.cdnllnwnl.neulion.com/nlds_vod/nba3/vod/2017/10/17/nlncp/21700001/2_21700001_bos_cle_2017_tnt_whole_1_6000_ipad.mp4.m3u8?h=a3ca5890849d7f31214b20c114812b3a.1508502489591&hdnea=exp=1508502549~acl=/*~hmac=5ACB05ADFD0DD07A10D290F18566196AF4A143393DDAE1C57AD525B70EE64308&nltid=nba&nltdt=0&uid=123456|User-Agent=iTunes-AppleTV/4.1
`

I'm only running the versions for the Linux platform (in case this makes it easier to implement).

Thanks very much for considering.

**Comment by NapoleonWils0n** [comment]
hi mate

development has switched to a new python version of the script called pilfer
so i wont be doing any more work on the bash version

pilfer uses a new more advanced technique to chop up urls
and works on linux, mac, windows and freebsd

it catches pretty much all the urls from kodi except links that use a local proxy

[pilfer github page](https://github.com/NapoleonWils0n/pilfer)  

[pilfer youtube videos](https://www.youtube.com/watch?v=uKRU74Uqj1s&list=PL7hhhG5qUoXmtylBpTV4AdjFkYOj2soEB)
