### ISSUE TITLE
.ripconfig: Improvements

### ISSUE THREAD

**Issue by K3rm1t4** [NapoleonWils0n/kodi-playercorefactory#93]
A short list of improvements regarding the .ripconfig file and its usage I'd like to see:
1) Add parameter to allow user-configurable 'default' folder (AFAIK currently hard coded to $HOME/Desktop)
2) Make rip-ytdl use this configuration file as well (AFAIK currently files are downloaded to directory where script is executed from)

I'd be really helpful if those features could be incorporated.
Thanks again.

**Comment by NapoleonWils0n** [comment]
hi mate

rip-ytdl is just a wrapper around youtube-dl

if you look at the youtube-dl man page under configuration 
you'll see there is option to specify a directory to save videos too

the option you want is -o ~/Movies/%(title)s%.(ext)s

that will save videos to your home Movies folder
