### ISSUE TITLE
Running 2 programs

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#94]
Hi NapoleonWilson, 

I got a silly question here, can I run rip-record and pilfer at the same time, would it interfear with each other  
and I dont know if pilfer can record a batch of file in a folder? That's why i liked rip-record.

                                                                                                             Thank You
                                                                                                                  Steve

**Comment by NapoleonWils0n** [comment]
hi steve, good to hear from you mate

yes you can use pilfrer and rip-record batch recordng at the same time
you can also copy the rip-record-batch.sh and change it to use pilfer and do batch recording with pilfer

make a copy of rip-record-batch.sh and call it pilfer-batch.sh

then change the code below in pilfer-batch.sh

```
#!/bin/bash

[[ $# -eq 0 ]] || exit; read -erp "enter a directory path: " DIR
[ -d $DIR ] && find $DIR -maxdepth 1 -name '*.txt' -type f -print0 | xargs -i -0 rip-record '{}' || echo no directory
```

change 
xargs -i -0 rip-record '{}'

to
xargs -i -0 pilfer -i  '{}'

so the final code should look like this

```
#!/bin/bash

[[ $# -eq 0 ]] || exit; read -erp "enter a directory path: " DIR
[ -d $DIR ] && find $DIR -maxdepth 1 -name '*.txt' -type f -print0 | xargs -i -0 pilfer-i '{}' || echo no directory
```

then put the pilfer-batch.sh in the bin folder in your home
and then source your bashrc file

open the terminal and type

source ~/.bashrc

i think that should work

also im just finishing off pilfer 2.0 which will let you record just the audio from a video stream
or record an audio stream like radio from kodi

hope that helps

**Comment by steve55792** [comment]
Hi NapoleonWilson , 
Sorry for the late response but the info you sent to me above, is that for ubuntu or windows? I look it all n the windows and i couldnt find any files to change. But I redownloaded Rip-record for windows again and also have pilfer still on the computer.

**Comment by NapoleonWils0n** [comment]
hi mate

the pilfer and rip-record installers cant be used on the same windows machine
you have to use one or the other

you can run pilfer and rip-record at the same time on linux but not windows

you should just be able to run the m3u8-link-checker on linux and give it a m3u8 file to process

**Comment by steve55792** [comment]
Hi NapoleonWilson,

yeah Im only usinng the rip-record for the rip-record-batch cause i see the pilfer for right now don't have a way to record one after another like rip-record-batch does. I'm on windows 7 right now.
