### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#95]
Hi NapoleonWilson:

Im curious, is there an easy way to scrape video links from websites to play later in vlc or mpv players or even to play in Kodi? I found a good website that shows old classic tv shows i like.

                                                                                                                        Steve

**Comment by NapoleonWils0n** [comment]
hi mate

you could use the network inspector in your browser
or use wireshark

but you may find urlsnooper easier to use,
i have seen kodi forum posts where people recommend urlsnooper for finding links for kodi

https://www.donationcoder.com/Software/Mouser/urlsnooper/

havent tried urlsnooper myself as im not a windows user

hope that helps

**Comment by steve55792** [comment]
Url Snooper did not work of grabbing the right urls . Thank you for helping. Havent tried wireshark.

**Comment by steve55792** [comment]
Would be cool if there's a way with rip-record or pilfer o pickup the links of websites. Dont know if there is a way.

**Comment by NapoleonWils0n** [comment]
hi mate

rip-record and pilfer are designed to work with kodi which gets the url for you

They will work with urls from other sources, 
but you have to get the url using other tools like wireshark or the browsers network tab

have you tried using youtube-dl on the website, youtube-dl works with lots of sites not just youtube

i made lots of videos about installing and using wireshark to find urls
if you search for hak-tip on youtube they have lots of videos about wireshark as well

pilfer and rip-record are designed to just do one job and thats to record urls
there are already other tools to capture network traffic so wouldnt make sense to reinvent the wheel

also i dont know enough python to create a website scraper, and i dont know if its possible with bash
