### ISSUE TITLE
will this work

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#98]
Hi NapoleonWilson, I was wondering if these commands i have for windows will work for Ubuntu:
recording:
![recording](https://user-images.githubusercontent.com/192039/39268693-2e0422c4-4896-11e8-8571-f9eabeeee9c8.PNG)

**Comment by NapoleonWils0n** [comment]
no windows commands like schtasks and bat files wont work on linux

**Comment by NapoleonWils0n** [comment]
if you want to schedule recordings there is a read me here

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/docs/schedule-recordings

with a link to a video as well

**Comment by steve55792** [comment]
Thank you NapoleonWilson for the info about recording in ubuntu.
