### ISSUE TITLE
Quick Recording

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#99]
Good morning NapoleonWilson,
Im on Ubuntu right now and was wondering when i try to record single or in a batch videos it said finsihed recording 3 to 4 seconds after i click record, and no video saved.

                                                                                                      Thanks
                                                                                                      Steve

**Comment by NapoleonWils0n** [comment]
hi mate

i seem to remeber that happens with old versions of ffmpeg
you need ffmpeg version 3.20 and above

if you run this command in the terminal it will give you the ffmpeg version

```
ffmpeg
```

if the ffmpeg version is less than 3.20 youll need to find a newerr version

you could also try using pilfer

**Comment by steve55792** [comment]
The pilfer was easy to setup and easy to use in ubuntu. Thank you.

**Comment by NapoleonWils0n** [comment]
hi mate

no problem 
pilfer is more advanced than rip-record an should catch more urls and downliad faster
